use super::diagram::Diagram;
use super::geom::{Place, V2};

// Generated by scripts/figure.py. Edit the Python plates, then:
//     python3 scripts/figure.py --write

/// I.1 — equilateral triangle on AB. C above the base; D, E on the sides.
pub fn book1_prop1() -> Diagram {
    let mut d = Diagram::new();
    d.put("A", V2::new(0.0, 0.0), Place::Left);
    d.put("B", V2::new(240.0, 0.0), Place::Right);
    d.put("C", V2::new(120.0, 207.846), Place::Above);
    d.circle("BCD", "A", "B");
    d.circle("ACE", "B", "A");
    d.in_circle("D", "A", "B", 180.0);
    d.in_circle("E", "B", "A", 0.0);
    d.join("A", "B");
    d.join("A", "C");
    d.join("B", "C");
    d.dots(&["A", "B", "C"]);
    d
}

/// I.2 — copy BC to A as AL. DAB (plate ∠ADB = 53.92°); DA, DB produced;
/// circles B, D. One scale: DA : DB : BC = 1 : 1.025 : 2.463.
pub fn book1_prop2() -> Diagram {
    let mut d = Diagram::new();
    d.put("D", V2::new(0.0, 0.0), Place::AboveLeft);
    d.put("A", V2::new(16.8999, -118.804), Place::Left);
    d.put("B", V2::new(108.606, -57.7126), Place::Deg(43.0));
    d.put("C", V2::new(108.606, 237.904), Place::Above);
    d.put("L", V2::new(58.9528, -414.432), Place::Deg(-117.0));
    d.put("G", V2::new(369.653, -196.432), Place::Deg(23.0));
    d.put("E", V2::new(86.6838, -609.377), Place::Deg(-98.0));
    d.put("F", V2::new(512.694, -272.444), Place::Deg(-10.0));
    d.circle("CGH", "B", "C");
    d.circle("GKL", "D", "G");
    d.on_circle("H", "B", "C", 140.0);
    d.on_circle("K", "D", "G", 169.0);
    d.chain(&["D", "A", "L", "E"]);
    d.chain(&["D", "B", "G", "F"]);
    d.join("A", "B");
    d.join("B", "C");
    d.dots(&["A", "B", "C", "D", "G", "L"]);
    d.clip(
        V2::new(-442.604, -665.377),
        V2::new(568.694, 466.604),
    );
    d
}

/// I.3 — Fitzpatrick plate (Elements p. 10): AB the greater; C a short
/// given line above the left of the circle; AD = AE at A (∠DAE = 132.14°);
/// circle DEF. One scale: AD : AB = 1 : 2.189.
pub fn book1_prop3() -> Diagram {
    let mut d = Diagram::new();
    d.put("A", V2::new(0.0, 0.0), Place::Deg(-136.0));
    d.put("B", V2::new(394.071, 0.0), Place::Deg(-3.0));
    d.put("E", V2::new(180.0, 0.0), Place::Deg(56.0));
    d.pin("Cleft", V2::new(-44.4888, 241.524));
    d.pin("Cright", V2::new(139.831, 241.524));
    d.named_line("C", "Cleft", "Cright");
    d.on_line("C", "Cleft", "Cright", 0.5, Place::Above);
    d.circle("DEF", "A", "E");
    d.put("D", V2::new(-120.763, 133.478), Place::Deg(111.0));
    d.on_circle("F", "A", "E", -56.215);
    d.join("A", "D");
    d.chain(&["A", "E", "B"]);
    d.dots(&["A", "B", "D", "E"]);
    d.clip(
        V2::new(-220.0, -201.603),
        V2::new(446.071, 289.524),
    );
    d
}

/// I.4 — Fitzpatrick plate (Elements p. 10): two congruent scalene
/// triangles on one baseline. A along BC = 0.705, h/BC = 0.864, CE/BC = 0.364.
pub fn book1_prop4() -> Diagram {
    let mut d = Diagram::new();
    d.put("A", V2::new(70.456, 86.365), Place::Deg(93.0));
    d.put("B", V2::new(0.0, 0.0), Place::Deg(-177.0));
    d.put("C", V2::new(100.0, 0.0), Place::Deg(-4.0));
    d.put("D", V2::new(206.819, 86.365), Place::Deg(77.0));
    d.put("E", V2::new(136.363, 0.0), Place::Deg(179.0));
    d.put("F", V2::new(236.363, 0.0), Place::Deg(-4.0));
    d.join("A", "B");
    d.join("B", "C");
    d.join("C", "A");
    d.join("D", "E");
    d.join("E", "F");
    d.join("F", "D");
    d.dots(&["A", "B", "C", "D", "E", "F"]);
    d.bow("E", "F", -9.09);
    d
}

/// I.5 — Fitzpatrick plate (Elements p. 11): isosceles ABC, AB = AC;
/// equal sides produced to D and E; F on BD, AG = AF on AE; FC and GB.
/// One scale: AB : BF : FD = 1 : 0.333 : 0.542; ∠BAC = 43.43°, ∠(BG,CF) = 39.4°.
pub fn book1_prop5() -> Diagram {
    let mut d = Diagram::new();
    d.put("A", V2::new(0.0, 0.0), Place::Deg(97.0));
    d.put("B", V2::new(-36.999, -92.9036), Place::Deg(164.0));
    d.put("C", V2::new(36.999, -92.9036), Place::Deg(18.0));
    d.put("F", V2::new(-49.3197, -123.84), Place::Deg(171.0));
    d.put("G", V2::new(49.3197, -123.84), Place::Deg(10.0));
    d.put("D", V2::new(-69.3731, -174.194), Place::Deg(-127.0));
    d.put("E", V2::new(69.3731, -174.194), Place::Deg(-87.0));
    d.chain(&["A", "B", "F", "D"]);
    d.chain(&["A", "C", "G", "E"]);
    d.join("B", "C");
    d.join("F", "C");
    d.join("G", "B");
    d.dots(&["A", "B", "C", "D", "E", "F", "G"]);
    d
}
