use super::{s, Proposition};
use crate::figure::{
    book1_prop1, book1_prop2, book1_prop3, book1_prop4, book1_prop5, book1_prop6,
    book1_prop7,
};

pub const PROP_1: Proposition = Proposition {
    book: 1,
    number: 1,
    enunciation: "To construct an equilateral triangle on a given finite straight-line.",
    figure: book1_prop1,
    phrases: &[
        s(1, "Let *AB* be the given finite straight-line."),
        s(2, "So it is required to construct an equilateral triangle on the straight-line *AB*."),
        s(3, "Let the circle *BCD* with center *A* and radius *AB* have been drawn,{[Post. 3]}"),
        s(3, "and again let the circle *ACE* with center *B* and radius *BA* have been drawn.{[Post. 3]}"),
        s(3, "And let the straight-lines *CA* and *CB* have been joined from the point *C*, where the circles cut one another, to the points *A* and *B* (respectively).{[Post. 1]}"),
        s(4, "And since the point *A* is the center of the circle *CDB*, *AC* is equal to *AB*.{[Def. 1.15]}"),
        s(4, "Again, since the point *B* is the center of the circle *CAE*, *BC* is equal to *BA*.{[Def. 1.15]}"),
        s(4, "But *CA* was also shown (to be) equal to *AB*."),
        s(4, "Thus, *CA* and *CB* are each equal to *AB*."),
        s(4, "But things equal to the same thing are also equal to one another.{[C.N. 1]}"),
        s(4, "Thus, *CA* is also equal to *CB*."),
        s(4, "Thus, the three (straight-lines) *CA*, *AB*, and *BC* are equal to one another."),
        s(5, "Thus, the triangle *ABC* is equilateral, and has been constructed on the given finite straight-line *AB*."),
        s(5, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_2: Proposition = Proposition {
    book: 1,
    number: 2,
    enunciation: "To place a straight-line equal to a given straight-line at a given point (as an extremity).",
    figure: book1_prop2,
    phrases: &[
        s(1, "Let *A* be the given point, and *BC* the given straight-line."),
        s(1, "So it is required to place a straight-line at point *A* equal to the given straight-line *BC*."),
        s(2, "For let the straight-line *AB* have been joined from point *A* to point *B*,{[Post. 1]}"),
        s(2, "and let the equilateral triangle *DAB* have been constructed upon it.{[Prop. 1.1]}"),
        s(2, "And let the straight-lines *AE* and *BF* have been produced in a straight-line with *DA* and *DB* (respectively).{[Post. 2]}"),
        s(2, "And let the circle *CGH* with center *B* and radius *BC* have been drawn,{[Post. 3]}"),
        s(2, "and again let the circle *GKL* with center *D* and radius *DG* have been drawn.{[Post. 3]}"),
        s(3, "Therefore, since the point *B* is the center of (the circle) *CGH*, *BC* is equal to *BG*.{[Def. 1.15]}"),
        s(3, "Again, since the point *D* is the center of the circle *GKL*, *DL* is equal to *DG*.{[Def. 1.15]}"),
        s(3, "And within these, *DA* is equal to *DB*."),
        s(3, "Thus, the remainder *AL* is equal to the remainder *BG*.{[C.N. 3]}"),
        s(3, "But *BC* was also shown (to be) equal to *BG*."),
        s(3, "Thus, *AL* and *BC* are each equal to *BG*."),
        s(3, "But things equal to the same thing are also equal to one another.{[C.N. 1]}"),
        s(3, "Thus, *AL* is also equal to *BC*."),
        s(4, "Thus, the straight-line *AL*, equal to the given straight-line *BC*, has been placed at the given point *A*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_3: Proposition = Proposition {
    book: 1,
    number: 3,
    enunciation: "For two given unequal straight-lines, to cut off from the greater a straight-line equal to the lesser.",
    figure: book1_prop3,
    phrases: &[
        s(1, "Let *AB* and *C* be the two given unequal straight-lines, of which let the greater be *AB*."),
        s(1, "So it is required to cut off a straight-line equal to the lesser *C* from the greater *AB*."),
        s(2, "Let the line *AD*, equal to the straight-line *C*, have been placed at point *A*.{[Prop. 1.2]}"),
        s(2, "And let the circle *DEF* have been drawn with center *A* and radius *AD*.{[Post. 3]}"),
        s(3, "And since point *A* is the center of circle *DEF*, *AE* is equal to *AD*.{[Def. 1.15]}"),
        s(3, "But, *C* is also equal to *AD*."),
        s(3, "Thus, *AE* and *C* are each equal to *AD*."),
        s(3, "So *AE* is also equal to *C*.{[C.N. 1]}"),
        s(4, "Thus, for two given unequal straight-lines, *AB* and *C*, the (straight-line) *AE*, equal to the lesser *C*, has been cut off from the greater *AB*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_4: Proposition = Proposition {
    book: 1,
    number: 4,
    enunciation: "If two triangles have two sides equal to two sides, respectively, and have the angle(s) enclosed by the equal straight-lines equal, then they will also have the base equal to the base, and the triangle will be equal to the triangle, and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles.",
    figure: book1_prop4,
    phrases: &[
        s(1, "Let *ABC* and *DEF* be two triangles having the two sides *AB* and *AC* equal to the two sides *DE* and *DF*, respectively."),
        s(1, "(That is) *AB* to *DE*, and *AC* to *DF*."),
        s(1, "And (let) the angle *BAC* (be) equal to the angle *EDF*."),
        s(1, "I say that the base *BC* is also equal to the base *EF*,"),
        s(1, "and triangle *ABC* will be equal to triangle *DEF*,"),
        s(1, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles."),
        s(1, "(That is) *ABC* to *DEF*, and *ACB* to *DFE*."),
        s(2, "For if triangle *ABC* is applied to triangle *DEF*,"),
        s(2, "the point *A* being placed on the point *D*, and the straight-line *AB* on *DE*,"),
        s(2, "then the point *B* will also coincide with *E*, on account of *AB* being equal to *DE*."),
        s(2, "So (because of) *AB* coinciding with *DE*,"),
        s(2, "the straight-line *AC* will also coincide with *DF*, on account of the angle *BAC* being equal to *EDF*."),
        s(2, "So the point *C* will also coincide with the point *F*, again on account of *AC* being equal to *DF*."),
        s(2, "But, point *B* certainly also coincided with point *E*,"),
        s(2, "so that the base *BC* will coincide with the base *EF*."),
        s(2, "For if *B* coincides with *E*, and *C* with *F*,"),
        s(2, "and the base *BC* does not coincide with *EF*, then two straight-lines will encompass an area."),
        s(2, "The very thing is impossible.{[Post. 1]}"),
        s(2, "Thus, the base *BC* will coincide with *EF*, and will be equal to it.{[C.N. 4]}"),
        s(2, "So the whole triangle *ABC* will coincide with the whole triangle *DEF*, and will be equal to it.{[C.N. 4]}"),
        s(2, "And the remaining angles will coincide with the remaining angles, and will be equal to them.{[C.N. 4]}"),
        s(2, "(That is) *ABC* to *DEF*, and *ACB* to *DFE*.{[C.N. 4]}"),
        s(3, "Thus, if two triangles have two sides equal to two sides, respectively,"),
        s(3, "and have the angle(s) enclosed by the equal straight-line equal,"),
        s(3, "then they will also have the base equal to the base,"),
        s(3, "and the triangle will be equal to the triangle,"),
        s(3, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_5: Proposition = Proposition {
    book: 1,
    number: 5,
    enunciation: "For isosceles triangles, the angles at the base are equal to one another, and if the equal sides are produced then the angles under the base will be equal to one another.",
    figure: book1_prop5,
    phrases: &[
        s(1, "Let *ABC* be an isosceles triangle having the side *AB* equal to the side *AC*,"),
        s(1, "and let the straight-lines *BD* and *CE* have been produced in a straight-line with *AB* and *AC* (respectively).{[Post. 2]}"),
        s(1, "I say that the angle *ABC* is equal to *ACB*, and (angle) *CBD* to *BCE*."),
        s(2, "For let the point *F* have been taken at random on *BD*,"),
        s(2, "and let *AG* have been cut off from the greater *AE*, equal to the lesser *AF*.{[Prop. 1.3]}"),
        s(2, "Also, let the straight-lines *FC* and *GB* have been joined.{[Post. 1]}"),
        s(3, "In fact, since *AF* is equal to *AG*, and *AB* to *AC*,"),
        s(3, "the two (straight-lines) *FA*, *AC* are equal to the two (straight-lines) *GA*, *AB*, respectively."),
        s(3, "They also encompass a common angle, *FAG*."),
        s(3, "Thus, the base *FC* is equal to the base *GB*,"),
        s(3, "and the triangle *AFC* will be equal to the triangle *AGB*,"),
        s(3, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles.{[Prop. 1.4]}"),
        s(3, "(That is) *ACF* to *ABG*, and *AFC* to *AGB*."),
        s(4, "And since the whole of *AF* is equal to the whole of *AG*, within which *AB* is equal to *AC*,"),
        s(4, "the remainder *BF* is thus equal to the remainder *CG*.{[C.N. 3]}"),
        s(4, "But *FC* was also shown (to be) equal to *GB*."),
        s(4, "So the two (straight-lines) *BF*, *FC* are equal to the two (straight-lines) *CG*, *GB*, respectively,"),
        s(4, "and the angle *BFC* (is) equal to the angle *CGB*,"),
        s(4, "and the base *BC* is common to them."),
        s(4, "Thus, the triangle *BFC* will be equal to the triangle *CGB*,"),
        s(4, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles.{[Prop. 1.4]}"),
        s(4, "Thus, *FBC* is equal to *GCB*, and *BCF* to *CBG*."),
        s(5, "Therefore, since the whole angle *ABG* was shown (to be) equal to the whole angle *ACF*,"),
        s(5, "within which *CBG* is equal to *BCF*,"),
        s(5, "the remainder *ABC* is thus equal to the remainder *ACB*.{[C.N. 3]}"),
        s(5, "And they are at the base of triangle *ABC*."),
        s(5, "And *FBC* was also shown (to be) equal to *GCB*."),
        s(5, "And they are under the base."),
        s(6, "Thus, for isosceles triangles, the angles at the base are equal to one another,"),
        s(6, "and if the equal sides are produced then the angles under the base will be equal to one another."),
        s(6, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_6: Proposition = Proposition {
    book: 1,
    number: 6,
    enunciation: "If a triangle has two angles equal to one another then the sides subtending the equal angles will also be equal to one another.",
    figure: book1_prop6,
    phrases: &[
        s(1, "Let *ABC* be a triangle having the angle *ABC* equal to the angle *ACB*."),
        s(1, "I say that side *AB* is also equal to side *AC*."),
        s(2, "For if *AB* is unequal to *AC* then one of them is greater."),
        s(2, "Let *AB* be greater."),
        s(2, "And let *DB*, equal to the lesser *AC*, have been cut off from the greater *AB*.{[Prop. 1.3]}"),
        s(2, "And let *DC* have been joined.{[Post. 1]}"),
        s(3, "Therefore, since *DB* is equal to *AC*, and *BC* (is) common,"),
        s(3, "the two sides *DB*, *BC* are equal to the two sides *AC*, *CB*, respectively,"),
        s(3, "and the angle *DBC* is equal to the angle *ACB*."),
        s(3, "Thus, the base *DC* is equal to the base *AB*,"),
        s(3, "and the triangle *DBC* will be equal to the triangle *ACB*,{[Prop. 1.4]}"),
        s(3, "the lesser to the greater."),
        s(3, "The very notion (is) absurd.{[C.N. 5]}"),
        s(3, "Thus, *AB* is not unequal to *AC*."),
        s(3, "Thus, (it is) equal."),
        s(4, "Thus, if a triangle has two angles equal to one another then the sides subtending the equal angles will also be equal to one another."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_7: Proposition = Proposition {
    book: 1,
    number: 7,
    enunciation: "On the same straight-line, two other straight-lines equal, respectively, to two (given) straight-lines (which meet) cannot be constructed (meeting) at a different point on the same side (of the straight-line), but having the same ends as the given straight-lines.",
    figure: book1_prop7,
    phrases: &[
        s(1, "For, if possible, let the two straight-lines *AC*, *CB*, equal to two other straight-lines *AD*, *DB*, respectively, have been constructed on the same straight-line *AB*,"),
        s(1, "meeting at different points, *C* and *D*, on the same side (of *AB*), and having the same ends (on *AB*)."),
        s(1, "So *CA* is equal to *DA*, having the same end *A* as it,"),
        s(1, "and *CB* is equal to *DB*, having the same end *B* as it."),
        s(1, "And let *CD* have been joined.{[Post. 1]}"),
        s(2, "Therefore, since *AC* is equal to *AD*, the angle *ACD* is also equal to angle *ADC*.{[Prop. 1.5]}"),
        s(2, "Thus, *ADC* (is) greater than *DCB*.{[C.N. 5]}"),
        s(2, "Thus, *CDB* is much greater than *DCB*.{[C.N. 5]}"),
        s(2, "Again, since *CB* is equal to *DB*, the angle *CDB* is also equal to angle *DCB*.{[Prop. 1.5]}"),
        s(2, "But it was shown that the former (angle) is also much greater (than the latter)."),
        s(2, "The very thing is impossible."),
        s(3, "Thus, on the same straight-line, two other straight-lines equal, respectively, to two (given) straight-lines (which meet) cannot be constructed (meeting) at a different point on the same side (of the straight-line), but having the same ends as the given straight-lines."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROPOSITIONS: &[Proposition] = &[
    PROP_1, PROP_2, PROP_3, PROP_4, PROP_5, PROP_6, PROP_7,
];
