use super::{s, Proposition};
use crate::figure::{
    book1_prop1, book1_prop2, book1_prop3, book1_prop4, book1_prop5, book1_prop6,
    book1_prop7, book1_prop8, book1_prop9, book1_prop10, book1_prop11,
    book1_prop12, book1_prop13, book1_prop14, book1_prop15, book1_prop16,
    book1_prop17, book1_prop18, book1_prop19, book1_prop20, book1_prop21,
    book1_prop22, book1_prop23, book1_prop24, book1_prop25, book1_prop26,
    book1_prop27, book1_prop28, book1_prop29, book1_prop30,
    book1_prop31, book1_prop32,
};

pub const PROP_1: Proposition = Proposition {
    book: 1,
    number: 1,
    enunciation: "To construct an equilateral triangle on a given finite straight-line.",
    figure: book1_prop1,
    phrases: &[
        s(1, "Let *AB* be the given finite straight-line."),
        s(2, "So it is required to construct an equilateral triangle on the straight-line *AB*."),
        s(3, "Let the circle *BCD* with center *A* and radius *AB* have been drawn,{[Post. 3]}"),
        s(3, "and again let the circle *ACE* with center *B* and radius *BA* have been drawn.{[Post. 3]}"),
        s(3, "And let the straight-lines *CA* and *CB* have been joined from the point *C*, where the circles cut one another, to the points *A* and *B* (respectively).{[Post. 1]}"),
        s(4, "And since the point *A* is the center of the circle *CDB*, *AC* is equal to *AB*.{[Def. 1.15]}"),
        s(4, "Again, since the point *B* is the center of the circle *CAE*, *BC* is equal to *BA*.{[Def. 1.15]}"),
        s(4, "But *CA* was also shown (to be) equal to *AB*."),
        s(4, "Thus, *CA* and *CB* are each equal to *AB*."),
        s(4, "But things equal to the same thing are also equal to one another.{[C.N. 1]}"),
        s(4, "Thus, *CA* is also equal to *CB*."),
        s(4, "Thus, the three (straight-lines) *CA*, *AB*, and *BC* are equal to one another."),
        s(5, "Thus, the triangle *ABC* is equilateral, and has been constructed on the given finite straight-line *AB*."),
        s(5, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_2: Proposition = Proposition {
    book: 1,
    number: 2,
    enunciation: "To place a straight-line equal to a given straight-line at a given point (as an extremity).",
    figure: book1_prop2,
    phrases: &[
        s(1, "Let *A* be the given point, and *BC* the given straight-line."),
        s(1, "So it is required to place a straight-line at point *A* equal to the given straight-line *BC*."),
        s(2, "For let the straight-line *AB* have been joined from point *A* to point *B*,{[Post. 1]}"),
        s(2, "and let the equilateral triangle *DAB* have been constructed upon it.{[Prop. 1.1]}"),
        s(2, "And let the straight-lines *AE* and *BF* have been produced in a straight-line with *DA* and *DB* (respectively).{[Post. 2]}"),
        s(2, "And let the circle *CGH* with center *B* and radius *BC* have been drawn,{[Post. 3]}"),
        s(2, "and again let the circle *GKL* with center *D* and radius *DG* have been drawn.{[Post. 3]}"),
        s(3, "Therefore, since the point *B* is the center of (the circle) *CGH*, *BC* is equal to *BG*.{[Def. 1.15]}"),
        s(3, "Again, since the point *D* is the center of the circle *GKL*, *DL* is equal to *DG*.{[Def. 1.15]}"),
        s(3, "And within these, *DA* is equal to *DB*."),
        s(3, "Thus, the remainder *AL* is equal to the remainder *BG*.{[C.N. 3]}"),
        s(3, "But *BC* was also shown (to be) equal to *BG*."),
        s(3, "Thus, *AL* and *BC* are each equal to *BG*."),
        s(3, "But things equal to the same thing are also equal to one another.{[C.N. 1]}"),
        s(3, "Thus, *AL* is also equal to *BC*."),
        s(4, "Thus, the straight-line *AL*, equal to the given straight-line *BC*, has been placed at the given point *A*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_3: Proposition = Proposition {
    book: 1,
    number: 3,
    enunciation: "For two given unequal straight-lines, to cut off from the greater a straight-line equal to the lesser.",
    figure: book1_prop3,
    phrases: &[
        s(1, "Let *AB* and *C* be the two given unequal straight-lines, of which let the greater be *AB*."),
        s(1, "So it is required to cut off a straight-line equal to the lesser *C* from the greater *AB*."),
        s(2, "Let the line *AD*, equal to the straight-line *C*, have been placed at point *A*.{[Prop. 1.2]}"),
        s(2, "And let the circle *DEF* have been drawn with center *A* and radius *AD*.{[Post. 3]}"),
        s(3, "And since point *A* is the center of circle *DEF*, *AE* is equal to *AD*.{[Def. 1.15]}"),
        s(3, "But, *C* is also equal to *AD*."),
        s(3, "Thus, *AE* and *C* are each equal to *AD*."),
        s(3, "So *AE* is also equal to *C*.{[C.N. 1]}"),
        s(4, "Thus, for two given unequal straight-lines, *AB* and *C*, the (straight-line) *AE*, equal to the lesser *C*, has been cut off from the greater *AB*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_4: Proposition = Proposition {
    book: 1,
    number: 4,
    enunciation: "If two triangles have two sides equal to two sides, respectively, and have the angle(s) enclosed by the equal straight-lines equal, then they will also have the base equal to the base, and the triangle will be equal to the triangle, and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles.",
    figure: book1_prop4,
    phrases: &[
        s(1, "Let *ABC* and *DEF* be two triangles having the two sides *AB* and *AC* equal to the two sides *DE* and *DF*, respectively."),
        s(1, "(That is) *AB* to *DE*, and *AC* to *DF*."),
        s(1, "And (let) the angle *BAC* (be) equal to the angle *EDF*."),
        s(1, "I say that the base *BC* is also equal to the base *EF*,"),
        s(1, "and triangle *ABC* will be equal to triangle *DEF*,"),
        s(1, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles."),
        s(1, "(That is) *ABC* to *DEF*, and *ACB* to *DFE*."),
        s(2, "For if triangle *ABC* is applied to triangle *DEF*,"),
        s(2, "the point *A* being placed on the point *D*, and the straight-line *AB* on *DE*,"),
        s(2, "then the point *B* will also coincide with *E*, on account of *AB* being equal to *DE*."),
        s(2, "So (because of) *AB* coinciding with *DE*,"),
        s(2, "the straight-line *AC* will also coincide with *DF*, on account of the angle *BAC* being equal to *EDF*."),
        s(2, "So the point *C* will also coincide with the point *F*, again on account of *AC* being equal to *DF*."),
        s(2, "But, point *B* certainly also coincided with point *E*,"),
        s(2, "so that the base *BC* will coincide with the base *EF*."),
        s(2, "For if *B* coincides with *E*, and *C* with *F*,"),
        s(2, "and the base *BC* does not coincide with *EF*, then two straight-lines will encompass an area."),
        s(2, "The very thing is impossible.{[Post. 1]}"),
        s(2, "Thus, the base *BC* will coincide with *EF*, and will be equal to it.{[C.N. 4]}"),
        s(2, "So the whole triangle *ABC* will coincide with the whole triangle *DEF*, and will be equal to it.{[C.N. 4]}"),
        s(2, "And the remaining angles will coincide with the remaining angles, and will be equal to them.{[C.N. 4]}"),
        s(2, "(That is) *ABC* to *DEF*, and *ACB* to *DFE*.{[C.N. 4]}"),
        s(3, "Thus, if two triangles have two sides equal to two sides, respectively,"),
        s(3, "and have the angle(s) enclosed by the equal straight-line equal,"),
        s(3, "then they will also have the base equal to the base,"),
        s(3, "and the triangle will be equal to the triangle,"),
        s(3, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_5: Proposition = Proposition {
    book: 1,
    number: 5,
    enunciation: "For isosceles triangles, the angles at the base are equal to one another, and if the equal sides are produced then the angles under the base will be equal to one another.",
    figure: book1_prop5,
    phrases: &[
        s(1, "Let *ABC* be an isosceles triangle having the side *AB* equal to the side *AC*,"),
        s(1, "and let the straight-lines *BD* and *CE* have been produced in a straight-line with *AB* and *AC* (respectively).{[Post. 2]}"),
        s(1, "I say that the angle *ABC* is equal to *ACB*, and (angle) *CBD* to *BCE*."),
        s(2, "For let the point *F* have been taken at random on *BD*,"),
        s(2, "and let *AG* have been cut off from the greater *AE*, equal to the lesser *AF*.{[Prop. 1.3]}"),
        s(2, "Also, let the straight-lines *FC* and *GB* have been joined.{[Post. 1]}"),
        s(3, "In fact, since *AF* is equal to *AG*, and *AB* to *AC*,"),
        s(3, "the two (straight-lines) *FA*, *AC* are equal to the two (straight-lines) *GA*, *AB*, respectively."),
        s(3, "They also encompass a common angle, *FAG*."),
        s(3, "Thus, the base *FC* is equal to the base *GB*,"),
        s(3, "and the triangle *AFC* will be equal to the triangle *AGB*,"),
        s(3, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles.{[Prop. 1.4]}"),
        s(3, "(That is) *ACF* to *ABG*, and *AFC* to *AGB*."),
        s(3, "And since the whole of *AF* is equal to the whole of *AG*, within which *AB* is equal to *AC*,"),
        s(3, "the remainder *BF* is thus equal to the remainder *CG*.{[C.N. 3]}"),
        s(3, "But *FC* was also shown (to be) equal to *GB*."),
        s(3, "So the two (straight-lines) *BF*, *FC* are equal to the two (straight-lines) *CG*, *GB*, respectively,"),
        s(3, "and the angle *BFC* (is) equal to the angle *CGB*,"),
        s(3, "and the base *BC* is common to them."),
        s(3, "Thus, the triangle *BFC* will be equal to the triangle *CGB*,"),
        s(3, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles.{[Prop. 1.4]}"),
        s(3, "Thus, *FBC* is equal to *GCB*, and *BCF* to *CBG*."),
        s(3, "Therefore, since the whole angle *ABG* was shown (to be) equal to the whole angle *ACF*,"),
        s(3, "within which *CBG* is equal to *BCF*,"),
        s(3, "the remainder *ABC* is thus equal to the remainder *ACB*.{[C.N. 3]}"),
        s(3, "And they are at the base of triangle *ABC*."),
        s(3, "And *FBC* was also shown (to be) equal to *GCB*."),
        s(3, "And they are under the base."),
        s(4, "Thus, for isosceles triangles, the angles at the base are equal to one another,"),
        s(4, "and if the equal sides are produced then the angles under the base will be equal to one another."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_6: Proposition = Proposition {
    book: 1,
    number: 6,
    enunciation: "If a triangle has two angles equal to one another then the sides subtending the equal angles will also be equal to one another.",
    figure: book1_prop6,
    phrases: &[
        s(1, "Let *ABC* be a triangle having the angle *ABC* equal to the angle *ACB*."),
        s(1, "I say that side *AB* is also equal to side *AC*."),
        s(2, "For if *AB* is unequal to *AC* then one of them is greater."),
        s(2, "Let *AB* be greater."),
        s(2, "And let *DB*, equal to the lesser *AC*, have been cut off from the greater *AB*.{[Prop. 1.3]}"),
        s(2, "And let *DC* have been joined.{[Post. 1]}"),
        s(3, "Therefore, since *DB* is equal to *AC*, and *BC* (is) common,"),
        s(3, "the two sides *DB*, *BC* are equal to the two sides *AC*, *CB*, respectively,"),
        s(3, "and the angle *DBC* is equal to the angle *ACB*."),
        s(3, "Thus, the base *DC* is equal to the base *AB*,"),
        s(3, "and the triangle *DBC* will be equal to the triangle *ACB*,{[Prop. 1.4]}"),
        s(3, "the lesser to the greater."),
        s(3, "The very notion (is) absurd.{[C.N. 5]}"),
        s(3, "Thus, *AB* is not unequal to *AC*."),
        s(3, "Thus, (it is) equal."),
        s(4, "Thus, if a triangle has two angles equal to one another then the sides subtending the equal angles will also be equal to one another."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_7: Proposition = Proposition {
    book: 1,
    number: 7,
    enunciation: "On the same straight-line, two other straight-lines equal, respectively, to two (given) straight-lines (which meet) cannot be constructed (meeting) at a different point on the same side (of the straight-line), but having the same ends as the given straight-lines.",
    figure: book1_prop7,
    phrases: &[
        s(1, "For, if possible, let the two straight-lines *AC*, *CB*, equal to two other straight-lines *AD*, *DB*, respectively, have been constructed on the same straight-line *AB*,"),
        s(1, "meeting at different points, *C* and *D*, on the same side (of *AB*), and having the same ends (on *AB*)."),
        s(1, "So *CA* is equal to *DA*, having the same end *A* as it,"),
        s(1, "and *CB* is equal to *DB*, having the same end *B* as it."),
        s(1, "And let *CD* have been joined.{[Post. 1]}"),
        s(2, "Therefore, since *AC* is equal to *AD*, the angle *ACD* is also equal to angle *ADC*.{[Prop. 1.5]}"),
        s(2, "Thus, *ADC* (is) greater than *DCB*.{[C.N. 5]}"),
        s(2, "Thus, *CDB* is much greater than *DCB*.{[C.N. 5]}"),
        s(2, "Again, since *CB* is equal to *DB*, the angle *CDB* is also equal to angle *DCB*.{[Prop. 1.5]}"),
        s(2, "But it was shown that the former (angle) is also much greater (than the latter)."),
        s(2, "The very thing is impossible."),
        s(3, "Thus, on the same straight-line, two other straight-lines equal, respectively, to two (given) straight-lines (which meet) cannot be constructed (meeting) at a different point on the same side (of the straight-line), but having the same ends as the given straight-lines."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_8: Proposition = Proposition {
    book: 1,
    number: 8,
    enunciation: "If two triangles have two sides equal to two sides, respectively, and also have the base equal to the base, then they will also have equal the angles encompassed by the equal straight-lines.",
    figure: book1_prop8,
    phrases: &[
        s(1, "Let *ABC* and *DEF* be two triangles having the two sides *AB* and *AC* equal to the two sides *DE* and *DF*, respectively."),
        s(1, "(That is) *AB* to *DE*, and *AC* to *DF*."),
        s(1, "Let them also have the base *BC* equal to the base *EF*."),
        s(1, "I say that the angle *BAC* is also equal to the angle *EDF*."),
        s(2, "For if triangle *ABC* is applied to triangle *DEF*, the point *B* being placed on point *E*, and the straight-line *BC* on *EF*,"),
        s(2, "then point *C* will also coincide with *F*, on account of *BC* being equal to *EF*."),
        s(2, "So (because of) *BC* coinciding with *EF*, (the sides) *BA* and *CA* will also coincide with *ED* and *DF* (respectively)."),
        s(2, "For if base *BC* coincides with base *EF*, but the sides *AB* and *AC* do not coincide with *ED* and *DF* (respectively), but miss like *EG* and *GF* (in the above figure),"),
        s(2, "then we will have constructed upon the same straight-line, two other straight-lines equal, respectively, to two (given) straight-lines,"),
        s(2, "and (meeting) at a different point on the same side (of the straight-line), but having the same ends."),
        s(2, "But (such straight-lines) cannot be constructed.{[Prop. 1.7]}"),
        s(2, "Thus, the base *BC* being applied to the base *EF*, the sides *BA* and *AC* cannot not coincide with *ED* and *DF* (respectively)."),
        s(2, "Thus, they will coincide."),
        s(2, "So the angle *BAC* will also coincide with angle *EDF*, and will be equal to it.{[C.N. 4]}"),
        s(3, "Thus, if two triangles have two sides equal to two side, respectively, and have the base equal to the base,"),
        s(3, "then they will also have equal the angles encompassed by the equal straight-lines."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_9: Proposition = Proposition {
    book: 1,
    number: 9,
    enunciation: "To cut a given rectilinear angle in half.",
    figure: book1_prop9,
    phrases: &[
        s(1, "Let *BAC* be the given rectilinear angle."),
        s(1, "So it is required to cut it in half."),
        s(2, "Let the point *D* have been taken at random on *AB*, and let *AE*, equal to *AD*, have been cut off from *AC,*{[Prop. 1.3]} and let *DE* have been joined."),
        s(2, "And let the equilateral triangle *DEF* have been constructed upon *DE,*{[Prop. 1.1]} and let *AF* have been joined."),
        s(2, "I say that the angle *BAC* has been cut in half by the straight-line *AF*."),
        s(3, "For since *AD* is equal to *AE*, and *AF* is common, the two (straight-lines) *DA*, *AF* are equal to the two (straight-lines) *EA*, *AF*, respectively."),
        s(3, "And the base *DF* is equal to the base *EF*."),
        s(3, "Thus, angle *DAF* is equal to angle *EAF*.{[Prop. 1.8]}"),
        s(4, "Thus, the given rectilinear angle *BAC* has been cut in half by the straight-line *AF*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_10: Proposition = Proposition {
    book: 1,
    number: 10,
    enunciation: "To cut a given finite straight-line in half.",
    figure: book1_prop10,
    phrases: &[
        s(1, "Let *AB* be the given finite straight-line."),
        s(1, "So it is required to cut the finite straight-line *AB* in half."),
        s(2, "Let the equilateral triangle *ABC* have been constructed upon (*AB*),{[Prop. 1.1]} and let the angle *ACB* have been cut in half by the straight-line *CD*.{[Prop. 1.9]}"),
        s(2, "I say that the straight-line *AB* has been cut in half at point *D*."),
        s(3, "For since *AC* is equal to *CB*, and *CD* (is) common, the two (straight-lines) *AC*, *CD* are equal to the two (straight-lines) *BC*, *CD*, respectively."),
        s(3, "And the angle *ACD* is equal to the angle *BCD*."),
        s(3, "Thus, the base *AD* is equal to the base *BD*.{[Prop. 1.4]}"),
        s(4, "Thus, the given finite straight-line *AB* has been cut in half at (point) *D*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_11: Proposition = Proposition {
    book: 1,
    number: 11,
    enunciation: "To draw a straight-line at right-angles to a given straight-line from a given point on it.",
    figure: book1_prop11,
    phrases: &[
        s(1, "Let *AB* be the given straight-line, and *C* the given point on it."),
        s(1, "So it is required to draw a straight-line from the point *C* at right-angles to the straight-line *AB*."),
        s(2, "Let the point *D* be have been taken at random on *AC*, and let *CE* be made equal to *CD,*{[Prop. 1.3]} and let the equilateral triangle *FDE* have been constructed on *DE,*{[Prop. 1.1]} and let *FC* have been joined."),
        s(2, "I say that the straight-line *FC* has been drawn at right-angles to the given straight-line *AB* from the given point *C* on it."),
        s(3, "For since *DC* is equal to *CE*, and *CF* is common, the two (straight-lines) *DC*, *CF* are equal to the two (straight-lines) *EC*, *CF*, respectively."),
        s(3, "And the base *DF* is equal to the base *FE*."),
        s(3, "Thus, the angle *DCF* is equal to the angle *ECF*,{[Prop. 1.8]} and they are adjacent."),
        s(3, "But when a straight-line stood on a(nother) straight-line makes the adjacent angles equal to one another, each of the equal angles is a right-angle.{[Def. 1.10]}"),
        s(3, "Thus, each of the (angles) *DCF* and *FCE* is a right-angle."),
        s(4, "Thus, the straight-line *CF* has been drawn at right-angles to the given straight-line *AB* from the given point *C* on it."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_12: Proposition = Proposition {
    book: 1,
    number: 12,
    enunciation: "To draw a straight-line perpendicular to a given infinite straight-line from a given point which is not on it.",
    figure: book1_prop12,
    phrases: &[
        s(1, "Let *AB* be the given infinite straight-line and *C* the given point, which is not on (*AB*)."),
        s(1, "So it is required to draw a straight-line perpendicular to the given infinite straight-line *AB* from the given point *C*, which is not on (*AB*)."),
        s(2, "For let point *D* have been taken at random on the other side (to *C*) of the straight-line *AB*, and let the circle *EFG* have been drawn with center *C* and radius *CD,*{[Post. 3]} and let the straight-line *EG* have been cut in half at (point) *H,*{[Prop. 1.10]} and let the straight-lines *CG*, *CH*, and *CE* have been joined."),
        s(2, "I say that the (straight-line) *CH* has been drawn perpendicular to the given infinite straight-line *AB* from the given point *C*, which is not on (*AB*)."),
        s(3, "For since *GH* is equal to *HE*, and *HC* (is) common, the two (straight-lines) *GH*, *HC* are equal to the two (straight-lines) *EH*, *HC*, respectively, and the base *CG* is equal to the base *CE*."),
        s(3, "Thus, the angle *CHG* is equal to the angle *EHC,*{[Prop. 1.8]} and they are adjacent."),
        s(3, "But when a straight-line stood on a(nother) straight-line makes the adjacent angles equal to one another, each of the equal angles is a right-angle, and the former straight-line is called a perpendicular to that upon which it stands.{[Def. 1.10]}"),
        s(4, "Thus, the (straight-line) *CH* has been drawn perpendicular to the given infinite straight-line *AB* from the given point *C*, which is not on (*AB*)."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_13: Proposition = Proposition {
    book: 1,
    number: 13,
    enunciation: "If a straight-line stood on a(nother) straight-line makes angles, it will certainly either make two right-angles, or (angles whose sum is) equal to two right-angles.",
    figure: book1_prop13,
    phrases: &[
        s(1, "For let some straight-line *AB* stood on the straight-line *CD* make the angles *CBA* and *ABD*."),
        s(1, "I say that the angles *CBA* and *ABD* are certainly either two right-angles, or (have a sum) equal to two right-angles."),
        s(2, "In fact, if *CBA* is equal to *ABD* then they are two right-angles.{[Def. 1.10]}"),
        s(2, "But, if not, let *BE* have been drawn from the point *B* at right-angles to *CD*.{[Prop. 1.11]}"),
        s(2, "Thus, *CBE* and *EBD* are two right-angles."),
        s(2, "And since *CBE* is equal to the two (angles) *CBA* and *ABE*, let *EBD* have been added to both."),
        s(2, "Thus, the (sum of the angles) *CBE* and *EBD* is equal to the (sum of the) three (angles) *CBA*, *ABE*, and *EBD*.{[C.N. 2]}"),
        s(2, "Again, since *DBA* is equal to the two (angles) *DBE* and *EBA*, let *ABC* have been added to both."),
        s(2, "Thus, the (sum of the angles) *DBA* and *ABC* is equal to the (sum of the) three (angles) *DBE*, *EBA*, and *ABC*.{[C.N. 2]}"),
        s(2, "But (the sum of) *CBE* and *EBD* was also shown (to be) equal to the (sum of the) same three (angles)."),
        s(2, "And things equal to the same thing are also equal to one another.{[C.N. 1]}"),
        s(2, "Therefore, (the sum of) *CBE* and *EBD* is also equal to (the sum of) *DBA* and *ABC*."),
        s(2, "But, (the sum of) *CBE* and *EBD* is two right-angles."),
        s(2, "Thus, (the sum of) *ABD* and *ABC* is also equal to two right-angles."),
        s(3, "Thus, if a straight-line stood on a(nother) straight-line makes angles, it will certainly either make two right-angles, or (angles whose sum is) equal to two right-angles."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_14: Proposition = Proposition {
    book: 1,
    number: 14,
    enunciation: "If two straight-lines, not lying on the same side, make adjacent angles (whose sum is) equal to two right-angles with some straight-line, at a point on it, then the two straight-lines will be straight-on (with respect) to one another.",
    figure: book1_prop14,
    phrases: &[
        s(1, "For let two straight-lines *BC* and *BD*, not lying on the same side, make adjacent angles *ABC* and *ABD* (whose sum is) equal to two right-angles with some straight-line *AB*, at the point *B* on it."),
        s(1, "I say that *BD* is straight-on with respect to *CB*."),
        s(2, "For if *BD* is not straight-on to *BC* then let *BE* be straight-on to *CB*."),
        s(3, "Therefore, since the straight-line *AB* stands on the straight-line *CBE*, the (sum of the) angles *ABC* and *ABE* is thus equal to two right-angles.{[Prop. 1.13]}"),
        s(3, "But (the sum of) *ABC* and *ABD* is also equal to two right-angles."),
        s(3, "Thus, (the sum of angles) *CBA* and *ABE* is equal to (the sum of angles) *CBA* and *ABD*.{[C.N. 1]}"),
        s(3, "Let (angle) *CBA* have been subtracted from both."),
        s(3, "Thus, the remainder *ABE* is equal to the remainder *ABD*,{[C.N. 3]} the lesser to the greater."),
        s(3, "The very thing is impossible."),
        s(3, "Thus, *BE* is not straight-on with respect to *CB*."),
        s(3, "Similarly, we can show that neither (is) any other (straight-line) than *BD*."),
        s(3, "Thus, *CB* is straight-on with respect to *BD*."),
        s(4, "Thus, if two straight-lines, not lying on the same side, make adjacent angles (whose sum is) equal to two right-angles with some straight-line, at a point on it, then the two straight-lines will be straight-on (with respect) to one another."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_15: Proposition = Proposition {
    book: 1,
    number: 15,
    enunciation: "If two straight-lines cut one another then they make the vertically opposite angles equal to one another.",
    figure: book1_prop15,
    phrases: &[
        s(1, "For let the two straight-lines *AB* and *CD* cut one another at the point *E*."),
        s(1, "I say that angle *AEC* is equal to (angle) *DEB*, and (angle) *CEB* to (angle) *AED*."),
        s(2, "For since the straight-line *AE* stands on the straight-line *CD*, making the angles *CEA* and *AED*, the (sum of the) angles *CEA* and *AED* is thus equal to two right-angles.{[Prop. 1.13]}"),
        s(2, "Again, since the straight-line *DE* stands on the straight-line *AB*, making the angles *AED* and *DEB*, the (sum of the) angles *AED* and *DEB* is thus equal to two right-angles.{[Prop. 1.13]}"),
        s(2, "But (the sum of) *CEA* and *AED* was also shown (to be) equal to two right-angles."),
        s(2, "Thus, (the sum of) *CEA* and *AED* is equal to (the sum of) *AED* and *DEB*.{[C.N. 1]}"),
        s(2, "Let *AED* have been subtracted from both."),
        s(2, "Thus, the remainder *CEA* is equal to the remainder *BED*.{[C.N. 3]}"),
        s(2, "Similarly, it can be shown that *CEB* and *DEA* are also equal."),
        s(3, "Thus, if two straight-lines cut one another then they make the vertically opposite angles equal to one another."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_16: Proposition = Proposition {
    book: 1,
    number: 16,
    enunciation: "For any triangle, when one of the sides is produced, the external angle is greater than each of the internal and opposite angles.",
    figure: book1_prop16,
    phrases: &[
        s(1, "Let *ABC* be a triangle, and let one of its sides *BC* have been produced to *D*."),
        s(1, "I say that the external angle *ACD* is greater than each of the internal and opposite angles, *CBA* and *BAC*."),
        s(2, "Let the (straight-line) *AC* have been cut in half at (point) *E*.{[Prop. 1.10]}"),
        s(2, "And *BE* being joined, let it have been produced in a straight-line to (point) *F*."),
        s(2, "And let *EF* be made equal to *BE*,{[Prop. 1.3]} and let *FC* have been joined, and let *AC* have been drawn through to (point) *G*."),
        s(3, "Therefore, since *AE* is equal to *EC*, and *BE* to *EF*, the two (straight-lines) *AE*, *EB* are equal to the two (straight-lines) *CE*, *EF*, respectively."),
        s(3, "Also, angle *AEB* is equal to angle *FEC*, for (they are) vertically opposite.{[Prop. 1.15]}"),
        s(3, "Thus, the base *AB* is equal to the base *FC*, and the triangle *ABE* is equal to the triangle *FEC*, and the remaining angles subtended by the equal sides are equal to the corresponding remaining angles.{[Prop. 1.4]}"),
        s(3, "Thus, *BAE* is equal to *ECF*."),
        s(3, "But *ECD* is greater than *ECF*."),
        s(3, "Thus, *ACD* is greater than *BAE*."),
        s(3, "Similarly, by having cut *BC* in half, it can be shown (that) *BCG*—that is to say, *ACD*—(is) also greater than *ABC*."),
        s(4, "Thus, for any triangle, when one of the sides is produced, the external angle is greater than each of the internal and opposite angles."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_17: Proposition = Proposition {
    book: 1,
    number: 17,
    enunciation: "For any triangle, (the sum of) two angles taken together in any (possible way) is less than two right-angles.",
    figure: book1_prop17,
    phrases: &[
        s(1, "Let *ABC* be a triangle."),
        s(1, "I say that (the sum of) two angles of triangle *ABC* taken together in any (possible way) is less than two right-angles."),
        s(2, "For let *BC* have been produced to *D*."),
        s(3, "And since the angle *ACD* is external to triangle *ABC*, it is greater than the internal and opposite angle *ABC*.{[Prop. 1.16]}"),
        s(3, "Let *ACB* have been added to both."),
        s(3, "Thus, the (sum of the angles) *ACD* and *ACB* is greater than the (sum of the angles) *ABC* and *BCA*."),
        s(3, "But, (the sum of) *ACD* and *ACB* is equal to two right-angles.{[Prop. 1.13]}"),
        s(3, "Thus, (the sum of) *ABC* and *BCA* is less than two right-angles."),
        s(3, "Similarly, we can show that (the sum of) *BAC* and *ACB* is also less than two right-angles, and further (that the sum of) *CAB* and *ABC* (is less than two right-angles)."),
        s(4, "Thus, for any triangle, (the sum of) two angles taken together in any (possible way) is less than two right-angles."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_18: Proposition = Proposition {
    book: 1,
    number: 18,
    enunciation: "In any triangle, the greater side subtends the greater angle.",
    figure: book1_prop18,
    phrases: &[
        s(1, "For let *ABC* be a triangle having side *AC* greater than *AB*."),
        s(1, "I say that angle *ABC* is also greater than *BCA*."),
        s(2, "For since *AC* is greater than *AB*, let *AD* be made equal to *AB*,{[Prop. 1.3]} and let *BD* have been joined."),
        s(3, "And since angle *ADB* is external to triangle *BCD*, it is greater than the internal and opposite (angle) *DCB*.{[Prop. 1.16]}"),
        s(3, "But *ADB* (is) equal to *ABD*, since side *AB* is also equal to side *AD*.{[Prop. 1.5]}"),
        s(3, "Thus, *ABD* is also greater than *ACB*."),
        s(3, "Thus, *ABC* is much greater than *ACB*."),
        s(4, "Thus, in any triangle, the greater side subtends the greater angle."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_19: Proposition = Proposition {
    book: 1,
    number: 19,
    enunciation: "In any triangle, the greater angle is subtended by the greater side.",
    figure: book1_prop19,
    phrases: &[
        s(1, "Let *ABC* be a triangle having the angle *ABC* greater than *BCA*."),
        s(1, "I say that side *AC* is also greater than side *AB*."),
        s(2, "For if not, *AC* is certainly either equal to, or less than, *AB*."),
        s(2, "In fact, *AC* is not equal to *AB*."),
        s(2, "For then angle *ABC* would also have been equal to *ACB*.{[Prop. 1.5]}"),
        s(2, "But it is not."),
        s(2, "Thus, *AC* is not equal to *AB*."),
        s(2, "Neither, indeed, is *AC* less than *AB*."),
        s(2, "For then angle *ABC* would also have been less than *ACB*.{[Prop. 1.18]}"),
        s(2, "But it is not."),
        s(2, "Thus, *AC* is not less than *AB*."),
        s(2, "But it was shown that (*AC*) is not equal (to *AB*) either."),
        s(2, "Thus, *AC* is greater than *AB*."),
        s(3, "Thus, in any triangle, the greater angle is subtended by the greater side."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_20: Proposition = Proposition {
    book: 1,
    number: 20,
    enunciation: "In any triangle, (the sum of) two sides taken together in any (possible way) is greater than the remaining (side).",
    figure: book1_prop20,
    phrases: &[
        s(1, "For let *ABC* be a triangle."),
        s(1, "I say that in triangle *ABC* (the sum of) two sides taken together in any (possible way) is greater than the remaining (side)."),
        s(1, "(So), (the sum of) *BA* and *AC* (is greater) than *BC*, (the sum of) *AB* and *BC* than *AC*, and (the sum of) *BC* and *CA* than *AB*."),
        s(2, "For let *BA* have been drawn through to point *D*, and let *AD* be made equal to *CA*,{[Prop. 1.3]} and let *DC* have been joined."),
        s(3, "Therefore, since *DA* is equal to *AC*, the angle *ADC* is also equal to *ACD*.{[Prop. 1.5]}"),
        s(3, "Thus, *BCD* is greater than *ADC*."),
        s(3, "And since *DCB* is a triangle having the angle *BCD* greater than *BDC*, and the greater angle subtends the greater side,{[Prop. 1.19]} *DB* is thus greater than *BC*."),
        s(3, "But *DA* is equal to *AC*."),
        s(3, "Thus, (the sum of) *BA* and *AC* is greater than *BC*."),
        s(3, "Similarly, we can show that (the sum of) *AB* and *BC* is also greater than *CA*, and (the sum of) *BC* and *CA* than *AB*."),
        s(4, "Thus, in any triangle, (the sum of) two sides taken together in any (possible way) is greater than the remaining (side)."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_21: Proposition = Proposition {
    book: 1,
    number: 21,
    enunciation: "If two internal straight-lines are constructed on one of the sides of a triangle, from its ends, the constructed (straight-lines) will be less than the two remaining sides of the triangle, but will encompass a greater angle.",
    figure: book1_prop21,
    phrases: &[
        s(1, "For let the two internal straight-lines *BD* and *DC* have been constructed on one of the sides *BC* of the triangle *ABC*, from its ends *B* and *C* (respectively)."),
        s(1, "I say that *BD* and *DC* are less than the (sum of the) two remaining sides of the triangle *BA* and *AC*, but encompass an angle *BDC* greater than *BAC*."),
        s(2, "For let *BD* have been drawn through to *E*."),
        s(2, "And since in any triangle (the sum of any) two sides is greater than the remaining (side),{[Prop. 1.20]} in triangle *ABE* the (sum of the) two sides *AB* and *AE* is thus greater than *BE*."),
        s(2, "Let *EC* have been added to both."),
        s(2, "Thus, (the sum of) *BA* and *AC* is greater than (the sum of) *BE* and *EC*."),
        s(2, "Again, since in triangle *CED* the (sum of the) two sides *CE* and *ED* is greater than *CD*, let *DB* have been added to both."),
        s(2, "Thus, (the sum of) *CE* and *EB* is greater than (the sum of) *CD* and *DB*."),
        s(2, "But, (the sum of) *BA* and *AC* was shown (to be) greater than (the sum of) *BE* and *EC*."),
        s(2, "Thus, (the sum of) *BA* and *AC* is much greater than (the sum of) *BD* and *DC*."),
        s(3, "Again, since in any triangle the external angle is greater than the internal and opposite (angles),{[Prop. 1.16]} in triangle *CDE* the external angle *BDC* is thus greater than *CED*."),
        s(3, "Accordingly, for the same (reason), the external angle *CEB* of the triangle *ABE* is also greater than *BAC*."),
        s(3, "But, *BDC* was shown (to be) greater than *CEB*."),
        s(3, "Thus, *BDC* is much greater than *BAC*."),
        s(4, "Thus, if two internal straight-lines are constructed on one of the sides of a triangle, from its ends, the constructed (straight-lines) are less than the two remaining sides of the triangle, but encompass a greater angle."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_22: Proposition = Proposition {
    book: 1,
    number: 22,
    enunciation: "To construct a triangle from three straight-lines which are equal to three given [straight-lines]. It is necessary for (the sum of) two (of the straight-lines) taken together in any (possible way) to be greater than the remaining (one), [on account of the (fact that) in any triangle (the sum of) two sides taken together in any (possible way) is greater than the remaining (one) [Prop. 1.20]].",
    figure: book1_prop22,
    phrases: &[
        s(1, "Let *A*, *B*, and *C* be the three given straight-lines, of which let (the sum of) two taken together in any (possible way) be greater than the remaining (one)."),
        s(1, "(Thus), (the sum of) *A* and *B* (is greater) than *C*, (the sum of) *A* and *C* than *B*, and also (the sum of) *B* and *C* than *A*."),
        s(1, "So it is required to construct a triangle from (straight-lines) equal to *A*, *B*, and *C*."),
        s(2, "Let some straight-line *DE* be set out, terminated at *D*, and infinite in the direction of *E*."),
        s(2, "And let *DF* made equal to *A*, and *FG* equal to *B*, and *GH* equal to *C*.{[Prop. 1.3]}"),
        s(2, "And let the circle *DKL* have been drawn with center *F* and radius *FD*."),
        s(2, "Again, let the circle *KLH* have been drawn with center *G* and radius *GH*."),
        s(2, "And let *KF* and *KG* have been joined."),
        s(2, "I say that the triangle *KFG* has been constructed from three straight-lines equal to *A*, *B*, and *C*."),
        s(3, "For since point *F* is the center of the circle *DKL*, *FD* is equal to *FK*."),
        s(3, "But, *FD* is equal to *A*."),
        s(3, "Thus, *KF* is also equal to *A*."),
        s(3, "Again, since point *G* is the center of the circle *LKH*, *GH* is equal to *GK*."),
        s(3, "But, *GH* is equal to *C*."),
        s(3, "Thus, *KG* is also equal to *C*."),
        s(3, "And *FG* is also equal to *B*."),
        s(3, "Thus, the three straight-lines *KF*, *FG*, and *GK* are equal to *A*, *B*, and *C* (respectively)."),
        s(4, "Thus, the triangle *KFG* has been constructed from the three straight-lines *KF*, *FG*, and *GK*, which are equal to the three given straight-lines *A*, *B*, and *C* (respectively)."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_23: Proposition = Proposition {
    book: 1,
    number: 23,
    enunciation: "To construct a rectilinear angle equal to a given rectilinear angle at a (given) point on a given straight-line.",
    figure: book1_prop23,
    phrases: &[
        s(1, "Let *AB* be the given straight-line, *A* the (given) point on it, and *DCE* the given rectilinear angle."),
        s(1, "So it is required to construct a rectilinear angle equal to the given rectilinear angle *DCE* at the (given) point *A* on the given straight-line *AB*."),
        s(2, "Let the points *D* and *E* have been taken at random on each of the (straight-lines) *CD* and *CE* (respectively), and let *DE* have been joined."),
        s(2, "And let the triangle *AFG* have been constructed from three straight-lines which are equal to *CD*, *DE*, and *CE*, such that *CD* is equal to *AF*, *CE* to *AG*, and further *DE* to *FG*.{[Prop. 1.22]}"),
        s(3, "Therefore, since the two (straight-lines) *DC*, *CE* are equal to the two (straight-lines) *FA*, *AG*, respectively, and the base *DE* is equal to the base *FG*, the angle *DCE* is thus equal to the angle *FAG*.{[Prop. 1.8]}"),
        s(4, "Thus, the rectilinear angle *FAG*, equal to the given rectilinear angle *DCE*, has been constructed at the (given) point *A* on the given straight-line *AB*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_24: Proposition = Proposition {
    book: 1,
    number: 24,
    enunciation: "If two triangles have two sides equal to two sides, respectively, but (one) has the angle encompassed by the equal straight-lines greater than the (corresponding) angle (in the other), (then the former triangle) will also have a base greater than the base (of the latter).",
    figure: book1_prop24,
    phrases: &[
        s(1, "Let *ABC* and *DEF* be two triangles having the two sides *AB* and *AC* equal to the two sides *DE* and *DF*, respectively."),
        s(1, "(That is), *AB* (equal) to *DE*, and *AC* to *DF*."),
        s(1, "Let them also have the angle at *A* greater than the angle at *D*."),
        s(1, "I say that the base *BC* is also greater than the base *EF*."),
        s(2, "For since angle *BAC* is greater than angle *EDF*, let (angle) *EDG*, equal to angle *BAC*, have been constructed at the point *D* on the straight-line *DE*.{[Prop. 1.23]}"),
        s(2, "And let *DG* have been made equal to either of *AC* or *DF*,{[Prop. 1.3]} and let *EG* and *FG* have been joined."),
        s(3, "Therefore, since *AB* is equal to *DE* and *AC* to *DG*, the two (straight-lines) *BA*, *AC* are equal to the two (straight-lines) *ED*, *DG*, respectively."),
        s(3, "Also the angle *BAC* is equal to the angle *EDG*."),
        s(3, "Thus, the base *BC* is equal to the base *EG*.{[Prop. 1.4]}"),
        s(3, "Again, since *DF* is equal to *DG*, angle *DGF* is also equal to angle *DFG*.{[Prop. 1.5]}"),
        s(3, "Thus, *DFG* (is) greater than *EGF*."),
        s(3, "Thus, *EFG* is much greater than *EGF*."),
        s(3, "And since triangle *EFG* has angle *EFG* greater than *EGF*, and the greater angle is subtended by the greater side,{[Prop. 1.19]} side *EG* (is) thus also greater than *EF*."),
        s(3, "But *EG* (is) equal to *BC*."),
        s(3, "Thus, *BC* (is) also greater than *EF*."),
        s(4, "Thus, if two triangles have two sides equal to two sides, respectively, but (one) has the angle encompassed by the equal straight-lines greater than the (corresponding) angle (in the other), (then the former triangle) will also have a base greater than the base (of the latter)."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_25: Proposition = Proposition {
    book: 1,
    number: 25,
    enunciation: "If two triangles have two sides equal to two sides, respectively, but (one) has a base greater than the base (of the other), then (the former triangle) will also have the angle encompassed by the equal straight-lines greater than the (corresponding) angle (in the latter).",
    figure: book1_prop25,
    phrases: &[
        s(1, "Let *ABC* and *DEF* be two triangles having the two sides *AB* and *AC* equal to the two sides *DE* and *DF*, respectively."),
        s(1, "(That is), *AB* (equal) to *DE*, and *AC* to *DF*."),
        s(1, "And let the base *BC* be greater than the base *EF*."),
        s(1, "I say that angle *BAC* is also greater than *EDF*."),
        s(2, "For if not, (*BAC*) is certainly either equal to, or less than, (*EDF*)."),
        s(2, "In fact, *BAC* is not equal to *EDF*."),
        s(2, "For then the base *BC* would also have been equal to the base *EF*.{[Prop. 1.4]}"),
        s(2, "But it is not."),
        s(2, "Thus, angle *BAC* is not equal to *EDF*."),
        s(2, "Neither, indeed, is *BAC* less than *EDF*."),
        s(2, "For then the base *BC* would also have been less than the base *EF*.{[Prop. 1.24]}"),
        s(2, "But it is not."),
        s(2, "Thus, angle *BAC* is not less than *EDF*."),
        s(2, "But it was shown that (*BAC* is) not equal (to *EDF*) either."),
        s(2, "Thus, *BAC* is greater than *EDF*."),
        s(3, "Thus, if two triangles have two sides equal to two sides, respectively, but (one) has a base greater than the base (of the other), then (the former triangle) will also have the angle encompassed by the equal straight-lines greater than the (corresponding) angle (in the latter)."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_26: Proposition = Proposition {
    book: 1,
    number: 26,
    enunciation: "If two triangles have two angles equal to two angles, respectively, and one side equal to one side—in fact, either that by the equal angles, or that subtending one of the equal angles—then (the triangles) will also have the remaining sides equal to the [corresponding] remaining sides, and the remaining angle (equal) to the remaining angle.",
    figure: book1_prop26,
    phrases: &[
        s(1, "Let *ABC* and *DEF* be two triangles having the two angles *ABC* and *BCA* equal to the two (angles) *DEF* and *EFD*, respectively."),
        s(1, "(That is) *ABC* (equal) to *DEF*, and *BCA* to *EFD*."),
        s(1, "And let them also have one side equal to one side."),
        s(1, "First of all, the (side) by the equal angles."),
        s(1, "(That is) *BC* (equal) to *EF*."),
        s(1, "I say that they will have the remaining sides equal to the corresponding remaining sides."),
        s(1, "(That is) *AB* (equal) to *DE*, and *AC* to *DF*."),
        s(1, "And (they will have) the remaining angle (equal) to the remaining angle."),
        s(1, "(That is) *BAC* (equal) to *EDF*."),
        s(2, "For if *AB* is unequal to *DE* then one of them is greater."),
        s(2, "Let *AB* be greater, and let *BG* be made equal to *DE*,{[Prop. 1.3]} and let *GC* have been joined."),
        s(3, "Therefore, since *BG* is equal to *DE*, and *BC* to *EF*, the two (straight-lines) *GB*, *BC* are equal to the two (straight-lines) *DE*, *EF*, respectively."),
        s(3, "And angle *GBC* is equal to angle *DEF*."),
        s(3, "Thus, the base *GC* is equal to the base *DF*, and triangle *GBC* is equal to triangle *DEF*, and the remaining angles subtended by the equal sides will be equal to the (corresponding) remaining angles.{[Prop. 1.4]}"),
        s(3, "Thus, *GCB* (is equal) to *DFE*."),
        s(3, "But, *DFE* was assumed (to be) equal to *BCA*."),
        s(3, "Thus, *BCG* is also equal to *BCA*, the lesser to the greater."),
        s(3, "The very thing (is) impossible."),
        s(3, "Thus, *AB* is not unequal to *DE*."),
        s(3, "Thus, (it is) equal."),
        s(3, "And *BC* is also equal to *EF*."),
        s(3, "So the two (straight-lines) *AB*, *BC* are equal to the two (straight-lines) *DE*, *EF*, respectively."),
        s(3, "And angle *ABC* is equal to angle *DEF*."),
        s(3, "Thus, the base *AC* is equal to the base *DF*, and the remaining angle *BAC* is equal to the remaining angle *EDF*.{[Prop. 1.4]}"),
        s(4, "But, again, let the sides subtending the equal angles be equal: for instance, (let) *AB* (be equal) to *DE*."),
        s(4, "Again, I say that the remaining sides will be equal to the remaining sides."),
        s(4, "(That is) *AC* (equal) to *DF*, and *BC* to *EF*."),
        s(4, "Furthermore, the remaining angle *BAC* is equal to the remaining angle *EDF*."),
        s(5, "For if *BC* is unequal to *EF* then one of them is greater."),
        s(5, "If possible, let *BC* be greater."),
        s(5, "And let *BH* be made equal to *EF*,{[Prop. 1.3]} and let *AH* have been joined."),
        s(5, "And since *BH* is equal to *EF*, and *AB* to *DE*, the two (straight-lines) *AB*, *BH* are equal to the two (straight-lines) *DE*, *EF*, respectively."),
        s(5, "And the angles they encompass (are also equal)."),
        s(5, "Thus, the base *AH* is equal to the base *DF*, and the triangle *ABH* is equal to the triangle *DEF*, and the remaining angles subtended by the equal sides will be equal to the (corresponding) remaining angles.{[Prop. 1.4]}"),
        s(5, "Thus, angle *BHA* is equal to *EFD*."),
        s(5, "But, *EFD* is equal to *BCA*."),
        s(5, "So, in triangle *AHC*, the external angle *BHA* is equal to the internal and opposite angle *BCA*."),
        s(5, "The very thing (is) impossible.{[Prop. 1.16]}"),
        s(5, "Thus, *BC* is not unequal to *EF*."),
        s(5, "Thus, (it is) equal."),
        s(5, "And *AB* is also equal to *DE*."),
        s(5, "So the two (straight-lines) *AB*, *BC* are equal to the two (straight-lines) *DE*, *EF*, respectively."),
        s(5, "And they encompass equal angles."),
        s(5, "Thus, the base *AC* is equal to the base *DF*, and triangle *ABC* (is) equal to triangle *DEF*, and the remaining angle *BAC* (is) equal to the remaining angle *EDF*.{[Prop. 1.4]}"),
        s(6, "Thus, if two triangles have two angles equal to two angles, respectively, and one side equal to one side—in fact, either that by the equal angles, or that subtending one of the equal angles—then (the triangles) will also have the remaining sides equal to the (corresponding) remaining sides, and the remaining angle (equal) to the remaining angle."),
        s(6, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_27: Proposition = Proposition {
    book: 1,
    number: 27,
    enunciation: "If a straight-line falling across two straight-lines makes the alternate angles equal to one another then the (two) straight-lines will be parallel to one another.",
    figure: book1_prop27,
    phrases: &[
        s(1, "For let the straight-line *EF*, falling across the two straight-lines *AB* and *CD*, make the alternate angles *AEF* and *EFD* equal to one another."),
        s(1, "I say that *AB* and *CD* are parallel."),
        s(2, "For if not, being produced, *AB* and *CD* will certainly meet together: either in the direction of *B* and *D*, or (in the direction) of *A* and *C*.{[Def. 1.23]}"),
        s(2, "Let them have been produced, and let them meet together in the direction of *B* and *D* at (point) *G*."),
        s(2, "So, for the triangle *GEF*, the external angle *AEF* is equal to the interior and opposite (angle) *EFG*."),
        s(2, "The very thing is impossible.{[Prop. 1.16]}"),
        s(2, "Thus, being produced, *AB* and *CD* will not meet together in the direction of *B* and *D*."),
        s(2, "Similarly, it can be shown that neither (will they meet together) in (the direction of) *A* and *C*."),
        s(2, "But (straight-lines) meeting in neither direction are parallel.{[Def. 1.23]}"),
        s(2, "Thus, *AB* and *CD* are parallel."),
        s(3, "Thus, if a straight-line falling across two straight-lines makes the alternate angles equal to one another then the (two) straight-lines will be parallel (to one another)."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_28: Proposition = Proposition {
    book: 1,
    number: 28,
    enunciation: "If a straight-line falling across two straight-lines makes the external angle equal to the internal and opposite angle on the same side, or (makes) the (sum of the) internal (angles) on the same side equal to two right-angles, then the (two) straight-lines will be parallel to one another.",
    figure: book1_prop28,
    phrases: &[
        s(1, "For let *EF*, falling across the two straight-lines *AB* and *CD*, make the external angle *EGB* equal to the internal and opposite angle *GHD*, or the (sum of the) internal (angles) on the same side, *BGH* and *GHD*, equal to two right-angles."),
        s(1, "I say that *AB* is parallel to *CD*."),
        s(2, "For since (in the first case) *EGB* is equal to *GHD*, but *EGB* is equal to *AGH*,{[Prop. 1.15]} *AGH* is thus also equal to *GHD*."),
        s(2, "And they are alternate (angles)."),
        s(2, "Thus, *AB* is parallel to *CD*.{[Prop. 1.27]}"),
        s(3, "Again, since (in the second case, the sum of) *BGH* and *GHD* is equal to two right-angles, and (the sum of) *AGH* and *BGH* is also equal to two right-angles,{[Prop. 1.13]} (the sum of) *AGH* and *BGH* is thus equal to (the sum of) *BGH* and *GHD*."),
        s(3, "Let *BGH* have been subtracted from both."),
        s(3, "Thus, the remainder *AGH* is equal to the remainder *GHD*."),
        s(3, "And they are alternate (angles)."),
        s(3, "Thus, *AB* is parallel to *CD*.{[Prop. 1.27]}"),
        s(4, "Thus, if a straight-line falling across two straight-lines makes the external angle equal to the internal and opposite angle on the same side, or (makes) the (sum of the) internal (angles) on the same side equal to two right-angles, then the (two) straight-lines will be parallel (to one another)."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_29: Proposition = Proposition {
    book: 1,
    number: 29,
    enunciation: "A straight-line falling across parallel straight-lines makes the alternate angles equal to one another, the external (angle) equal to the internal and opposite (angle), and the (sum of the) internal (angles) on the same side equal to two right-angles.",
    figure: book1_prop29,
    phrases: &[
        s(1, "For let the straight-line *EF* fall across the parallel straight-lines *AB* and *CD*."),
        s(1, "I say that it makes the alternate angles, *AGH* and *GHD*, equal, the external angle *EGB* equal to the internal and opposite (angle) *GHD*, and the (sum of the) internal (angles) on the same side, *BGH* and *GHD*, equal to two right-angles."),
        s(2, "For if *AGH* is unequal to *GHD* then one of them is greater."),
        s(2, "Let *AGH* be greater."),
        s(2, "Let *BGH* have been added to both."),
        s(2, "Thus, (the sum of) *AGH* and *BGH* is greater than (the sum of) *BGH* and *GHD*."),
        s(2, "But, (the sum of) *AGH* and *BGH* is equal to two right-angles.{[Prop. 1.13]}"),
        s(2, "Thus, (the sum of) *BGH* and *GHD* is also less than two right-angles."),
        s(2, "But (straight-lines) being produced to infinity from (internal angles whose sum is) less than two right-angles meet together.{[Post. 5]}"),
        s(2, "Thus, *AB* and *CD*, being produced to infinity, will meet together."),
        s(2, "But they do not meet, on account of them (initially) being assumed parallel (to one another).{[Def. 1.23]}"),
        s(2, "Thus, *AGH* is not unequal to *GHD*."),
        s(2, "Thus, (it is) equal."),
        s(2, "But, *AGH* is equal to *EGB*.{[Prop. 1.15]}"),
        s(2, "And *EGB* is thus also equal to *GHD*."),
        s(2, "Let *BGH* be added to both."),
        s(2, "Thus, (the sum of) *EGB* and *BGH* is equal to (the sum of) *BGH* and *GHD*."),
        s(2, "But, (the sum of) *EGB* and *BGH* is equal to two right-angles.{[Prop. 1.13]}"),
        s(2, "Thus, (the sum of) *BGH* and *GHD* is also equal to two right-angles."),
        s(3, "Thus, a straight-line falling across parallel straight-lines makes the alternate angles equal to one another, the external (angle) equal to the internal and opposite (angle), and the (sum of the) internal (angles) on the same side equal to two right-angles."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_30: Proposition = Proposition {
    book: 1,
    number: 30,
    enunciation: "(Straight-lines) parallel to the same straight-line are also parallel to one another.",
    figure: book1_prop30,
    phrases: &[
        s(1, "Let each of the (straight-lines) *AB* and *CD* be parallel to *EF*."),
        s(1, "I say that *AB* is also parallel to *CD*."),
        s(2, "For let the straight-line *GK* fall across (*AB*, *CD*, and *EF*)."),
        s(3, "And since the straight-line *GK* has fallen across the parallel straight-lines *AB* and *EF*, (angle) *AGK* (is) thus equal to *GHF*.{[Prop. 1.29]}"),
        s(3, "Again, since the straight-line *GK* has fallen across the parallel straight-lines *EF* and *CD*, (angle) *GHF* is equal to *GKD*.{[Prop. 1.29]}"),
        s(3, "But *AGK* was also shown (to be) equal to *GHF*."),
        s(3, "Thus, *AGK* is also equal to *GKD*."),
        s(3, "And they are alternate (angles)."),
        s(3, "Thus, *AB* is parallel to *CD*.{[Prop. 1.27]}"),
        s(4, "Thus, (straight-lines) parallel to the same straight-line are also parallel to one another."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_31: Proposition = Proposition {
    book: 1,
    number: 31,
    enunciation: "To draw a straight-line parallel to a given straight-line, through a given point.",
    figure: book1_prop31,
    phrases: &[
        s(1, "Let *A* be the given point, and *BC* the given straight-line."),
        s(1, "So it is required to draw a straight-line parallel to the straight-line *BC*, through the point *A*."),
        s(2, "Let the point *D* have been taken at random on *BC*, and let *AD* have been joined."),
        s(2, "And let (angle) *DAE*, equal to angle *ADC*, have been constructed on the straight-line *DA* at the point *A* on it.{[Prop. 1.23]}"),
        s(2, "And let the straight-line *AF* have been produced in a straight-line with *EA*."),
        s(3, "And since the straight-line *AD*, (in) falling across the two straight-lines *BC* and *EF*, has made the alternate angles *EAD* and *ADC* equal to one another, *EAF* is thus parallel to *BC*.{[Prop. 1.27]}"),
        s(4, "Thus, the straight-line *EAF* has been drawn parallel to the given straight-line *BC*, through the given point *A*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_32: Proposition = Proposition {
    book: 1,
    number: 32,
    enunciation: "In any triangle, (if) one of the sides (is) produced (then) the external angle is equal to the (sum of the) two internal and opposite (angles), and the (sum of the) three internal angles of the triangle is equal to two right-angles.",
    figure: book1_prop32,
    phrases: &[
        s(1, "Let *ABC* be a triangle, and let one of its sides *BC* have been produced to *D*."),
        s(1, "I say that the external angle *ACD* is equal to the (sum of the) two internal and opposite angles *CAB* and *ABC*, and the (sum of the) three internal angles of the triangle—*ABC*, *BCA*, and *CAB*—is equal to two right-angles."),
        s(2, "For let *CE* have been drawn through point *C* parallel to the straight-line *AB*.{[Prop. 1.31]}"),
        s(3, "And since *AB* is parallel to *CE*, and *AC* has fallen across them, the alternate angles *BAC* and *ACE* are equal to one another.{[Prop. 1.29]}"),
        s(3, "Again, since *AB* is parallel to *CE*, and the straight-line *BD* has fallen across them, the external angle *ECD* is equal to the internal and opposite (angle) *ABC*.{[Prop. 1.29]}"),
        s(3, "But *ACE* was also shown (to be) equal to *BAC*."),
        s(3, "Thus, the whole angle *ACD* is equal to the (sum of the) two internal and opposite (angles) *BAC* and *ABC*."),
        s(4, "Let *ACB* have been added to both."),
        s(4, "Thus, (the sum of) *ACD* and *ACB* is equal to the (sum of the) three (angles) *ABC*, *BCA*, and *CAB*."),
        s(4, "But, (the sum of) *ACD* and *ACB* is equal to two right-angles.{[Prop. 1.13]}"),
        s(4, "Thus, (the sum of) *ACB*, *CBA*, and *CAB* is also equal to two right-angles."),
        s(5, "Thus, in any triangle, (if) one of the sides (is) produced (then) the external angle is equal to the (sum of the) two internal and opposite (angles), and the (sum of the) three internal angles of the triangle is equal to two right-angles."),
        s(5, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROPOSITIONS: &[Proposition] = &[
    PROP_1, PROP_2, PROP_3, PROP_4, PROP_5, PROP_6, PROP_7, PROP_8, PROP_9, PROP_10, PROP_11,
    PROP_12, PROP_13, PROP_14, PROP_15, PROP_16, PROP_17, PROP_18, PROP_19, PROP_20, PROP_21,
    PROP_22, PROP_23, PROP_24, PROP_25, PROP_26, PROP_27, PROP_28, PROP_29, PROP_30,
    PROP_31, PROP_32,
];
