use super::{s, Proposition};
use crate::figure::{
    book1_prop1, book1_prop2, book1_prop3, book1_prop4, book1_prop5, book1_prop6,
    book1_prop7, book1_prop8, book1_prop9, book1_prop10, book1_prop11,
    book1_prop12, book1_prop13, book1_prop14, book1_prop15, book1_prop16,
    book1_prop17,
};

pub const PROP_1: Proposition = Proposition {
    book: 1,
    number: 1,
    enunciation: "To construct an equilateral triangle on a given finite straight-line.",
    figure: book1_prop1,
    phrases: &[
        s(1, "Let *AB* be the given finite straight-line."),
        s(2, "So it is required to construct an equilateral triangle on the straight-line *AB*."),
        s(3, "Let the circle *BCD* with center *A* and radius *AB* have been drawn,{[Post. 3]}"),
        s(3, "and again let the circle *ACE* with center *B* and radius *BA* have been drawn.{[Post. 3]}"),
        s(3, "And let the straight-lines *CA* and *CB* have been joined from the point *C*, where the circles cut one another, to the points *A* and *B* (respectively).{[Post. 1]}"),
        s(4, "And since the point *A* is the center of the circle *CDB*, *AC* is equal to *AB*.{[Def. 1.15]}"),
        s(4, "Again, since the point *B* is the center of the circle *CAE*, *BC* is equal to *BA*.{[Def. 1.15]}"),
        s(4, "But *CA* was also shown (to be) equal to *AB*."),
        s(4, "Thus, *CA* and *CB* are each equal to *AB*."),
        s(4, "But things equal to the same thing are also equal to one another.{[C.N. 1]}"),
        s(4, "Thus, *CA* is also equal to *CB*."),
        s(4, "Thus, the three (straight-lines) *CA*, *AB*, and *BC* are equal to one another."),
        s(5, "Thus, the triangle *ABC* is equilateral, and has been constructed on the given finite straight-line *AB*."),
        s(5, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_2: Proposition = Proposition {
    book: 1,
    number: 2,
    enunciation: "To place a straight-line equal to a given straight-line at a given point (as an extremity).",
    figure: book1_prop2,
    phrases: &[
        s(1, "Let *A* be the given point, and *BC* the given straight-line."),
        s(1, "So it is required to place a straight-line at point *A* equal to the given straight-line *BC*."),
        s(2, "For let the straight-line *AB* have been joined from point *A* to point *B*,{[Post. 1]}"),
        s(2, "and let the equilateral triangle *DAB* have been constructed upon it.{[Prop. 1.1]}"),
        s(2, "And let the straight-lines *AE* and *BF* have been produced in a straight-line with *DA* and *DB* (respectively).{[Post. 2]}"),
        s(2, "And let the circle *CGH* with center *B* and radius *BC* have been drawn,{[Post. 3]}"),
        s(2, "and again let the circle *GKL* with center *D* and radius *DG* have been drawn.{[Post. 3]}"),
        s(3, "Therefore, since the point *B* is the center of (the circle) *CGH*, *BC* is equal to *BG*.{[Def. 1.15]}"),
        s(3, "Again, since the point *D* is the center of the circle *GKL*, *DL* is equal to *DG*.{[Def. 1.15]}"),
        s(3, "And within these, *DA* is equal to *DB*."),
        s(3, "Thus, the remainder *AL* is equal to the remainder *BG*.{[C.N. 3]}"),
        s(3, "But *BC* was also shown (to be) equal to *BG*."),
        s(3, "Thus, *AL* and *BC* are each equal to *BG*."),
        s(3, "But things equal to the same thing are also equal to one another.{[C.N. 1]}"),
        s(3, "Thus, *AL* is also equal to *BC*."),
        s(4, "Thus, the straight-line *AL*, equal to the given straight-line *BC*, has been placed at the given point *A*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_3: Proposition = Proposition {
    book: 1,
    number: 3,
    enunciation: "For two given unequal straight-lines, to cut off from the greater a straight-line equal to the lesser.",
    figure: book1_prop3,
    phrases: &[
        s(1, "Let *AB* and *C* be the two given unequal straight-lines, of which let the greater be *AB*."),
        s(1, "So it is required to cut off a straight-line equal to the lesser *C* from the greater *AB*."),
        s(2, "Let the line *AD*, equal to the straight-line *C*, have been placed at point *A*.{[Prop. 1.2]}"),
        s(2, "And let the circle *DEF* have been drawn with center *A* and radius *AD*.{[Post. 3]}"),
        s(3, "And since point *A* is the center of circle *DEF*, *AE* is equal to *AD*.{[Def. 1.15]}"),
        s(3, "But, *C* is also equal to *AD*."),
        s(3, "Thus, *AE* and *C* are each equal to *AD*."),
        s(3, "So *AE* is also equal to *C*.{[C.N. 1]}"),
        s(4, "Thus, for two given unequal straight-lines, *AB* and *C*, the (straight-line) *AE*, equal to the lesser *C*, has been cut off from the greater *AB*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_4: Proposition = Proposition {
    book: 1,
    number: 4,
    enunciation: "If two triangles have two sides equal to two sides, respectively, and have the angle(s) enclosed by the equal straight-lines equal, then they will also have the base equal to the base, and the triangle will be equal to the triangle, and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles.",
    figure: book1_prop4,
    phrases: &[
        s(1, "Let *ABC* and *DEF* be two triangles having the two sides *AB* and *AC* equal to the two sides *DE* and *DF*, respectively."),
        s(1, "(That is) *AB* to *DE*, and *AC* to *DF*."),
        s(1, "And (let) the angle *BAC* (be) equal to the angle *EDF*."),
        s(1, "I say that the base *BC* is also equal to the base *EF*,"),
        s(1, "and triangle *ABC* will be equal to triangle *DEF*,"),
        s(1, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles."),
        s(1, "(That is) *ABC* to *DEF*, and *ACB* to *DFE*."),
        s(2, "For if triangle *ABC* is applied to triangle *DEF*,"),
        s(2, "the point *A* being placed on the point *D*, and the straight-line *AB* on *DE*,"),
        s(2, "then the point *B* will also coincide with *E*, on account of *AB* being equal to *DE*."),
        s(2, "So (because of) *AB* coinciding with *DE*,"),
        s(2, "the straight-line *AC* will also coincide with *DF*, on account of the angle *BAC* being equal to *EDF*."),
        s(2, "So the point *C* will also coincide with the point *F*, again on account of *AC* being equal to *DF*."),
        s(2, "But, point *B* certainly also coincided with point *E*,"),
        s(2, "so that the base *BC* will coincide with the base *EF*."),
        s(2, "For if *B* coincides with *E*, and *C* with *F*,"),
        s(2, "and the base *BC* does not coincide with *EF*, then two straight-lines will encompass an area."),
        s(2, "The very thing is impossible.{[Post. 1]}"),
        s(2, "Thus, the base *BC* will coincide with *EF*, and will be equal to it.{[C.N. 4]}"),
        s(2, "So the whole triangle *ABC* will coincide with the whole triangle *DEF*, and will be equal to it.{[C.N. 4]}"),
        s(2, "And the remaining angles will coincide with the remaining angles, and will be equal to them.{[C.N. 4]}"),
        s(2, "(That is) *ABC* to *DEF*, and *ACB* to *DFE*.{[C.N. 4]}"),
        s(3, "Thus, if two triangles have two sides equal to two sides, respectively,"),
        s(3, "and have the angle(s) enclosed by the equal straight-line equal,"),
        s(3, "then they will also have the base equal to the base,"),
        s(3, "and the triangle will be equal to the triangle,"),
        s(3, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_5: Proposition = Proposition {
    book: 1,
    number: 5,
    enunciation: "For isosceles triangles, the angles at the base are equal to one another, and if the equal sides are produced then the angles under the base will be equal to one another.",
    figure: book1_prop5,
    phrases: &[
        s(1, "Let *ABC* be an isosceles triangle having the side *AB* equal to the side *AC*,"),
        s(1, "and let the straight-lines *BD* and *CE* have been produced in a straight-line with *AB* and *AC* (respectively).{[Post. 2]}"),
        s(1, "I say that the angle *ABC* is equal to *ACB*, and (angle) *CBD* to *BCE*."),
        s(2, "For let the point *F* have been taken at random on *BD*,"),
        s(2, "and let *AG* have been cut off from the greater *AE*, equal to the lesser *AF*.{[Prop. 1.3]}"),
        s(2, "Also, let the straight-lines *FC* and *GB* have been joined.{[Post. 1]}"),
        s(3, "In fact, since *AF* is equal to *AG*, and *AB* to *AC*,"),
        s(3, "the two (straight-lines) *FA*, *AC* are equal to the two (straight-lines) *GA*, *AB*, respectively."),
        s(3, "They also encompass a common angle, *FAG*."),
        s(3, "Thus, the base *FC* is equal to the base *GB*,"),
        s(3, "and the triangle *AFC* will be equal to the triangle *AGB*,"),
        s(3, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles.{[Prop. 1.4]}"),
        s(3, "(That is) *ACF* to *ABG*, and *AFC* to *AGB*."),
        s(3, "And since the whole of *AF* is equal to the whole of *AG*, within which *AB* is equal to *AC*,"),
        s(3, "the remainder *BF* is thus equal to the remainder *CG*.{[C.N. 3]}"),
        s(3, "But *FC* was also shown (to be) equal to *GB*."),
        s(3, "So the two (straight-lines) *BF*, *FC* are equal to the two (straight-lines) *CG*, *GB*, respectively,"),
        s(3, "and the angle *BFC* (is) equal to the angle *CGB*,"),
        s(3, "and the base *BC* is common to them."),
        s(3, "Thus, the triangle *BFC* will be equal to the triangle *CGB*,"),
        s(3, "and the remaining angles subtended by the equal sides will be equal to the corresponding remaining angles.{[Prop. 1.4]}"),
        s(3, "Thus, *FBC* is equal to *GCB*, and *BCF* to *CBG*."),
        s(3, "Therefore, since the whole angle *ABG* was shown (to be) equal to the whole angle *ACF*,"),
        s(3, "within which *CBG* is equal to *BCF*,"),
        s(3, "the remainder *ABC* is thus equal to the remainder *ACB*.{[C.N. 3]}"),
        s(3, "And they are at the base of triangle *ABC*."),
        s(3, "And *FBC* was also shown (to be) equal to *GCB*."),
        s(3, "And they are under the base."),
        s(4, "Thus, for isosceles triangles, the angles at the base are equal to one another,"),
        s(4, "and if the equal sides are produced then the angles under the base will be equal to one another."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_6: Proposition = Proposition {
    book: 1,
    number: 6,
    enunciation: "If a triangle has two angles equal to one another then the sides subtending the equal angles will also be equal to one another.",
    figure: book1_prop6,
    phrases: &[
        s(1, "Let *ABC* be a triangle having the angle *ABC* equal to the angle *ACB*."),
        s(1, "I say that side *AB* is also equal to side *AC*."),
        s(2, "For if *AB* is unequal to *AC* then one of them is greater."),
        s(2, "Let *AB* be greater."),
        s(2, "And let *DB*, equal to the lesser *AC*, have been cut off from the greater *AB*.{[Prop. 1.3]}"),
        s(2, "And let *DC* have been joined.{[Post. 1]}"),
        s(3, "Therefore, since *DB* is equal to *AC*, and *BC* (is) common,"),
        s(3, "the two sides *DB*, *BC* are equal to the two sides *AC*, *CB*, respectively,"),
        s(3, "and the angle *DBC* is equal to the angle *ACB*."),
        s(3, "Thus, the base *DC* is equal to the base *AB*,"),
        s(3, "and the triangle *DBC* will be equal to the triangle *ACB*,{[Prop. 1.4]}"),
        s(3, "the lesser to the greater."),
        s(3, "The very notion (is) absurd.{[C.N. 5]}"),
        s(3, "Thus, *AB* is not unequal to *AC*."),
        s(3, "Thus, (it is) equal."),
        s(4, "Thus, if a triangle has two angles equal to one another then the sides subtending the equal angles will also be equal to one another."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_7: Proposition = Proposition {
    book: 1,
    number: 7,
    enunciation: "On the same straight-line, two other straight-lines equal, respectively, to two (given) straight-lines (which meet) cannot be constructed (meeting) at a different point on the same side (of the straight-line), but having the same ends as the given straight-lines.",
    figure: book1_prop7,
    phrases: &[
        s(1, "For, if possible, let the two straight-lines *AC*, *CB*, equal to two other straight-lines *AD*, *DB*, respectively, have been constructed on the same straight-line *AB*,"),
        s(1, "meeting at different points, *C* and *D*, on the same side (of *AB*), and having the same ends (on *AB*)."),
        s(1, "So *CA* is equal to *DA*, having the same end *A* as it,"),
        s(1, "and *CB* is equal to *DB*, having the same end *B* as it."),
        s(1, "And let *CD* have been joined.{[Post. 1]}"),
        s(2, "Therefore, since *AC* is equal to *AD*, the angle *ACD* is also equal to angle *ADC*.{[Prop. 1.5]}"),
        s(2, "Thus, *ADC* (is) greater than *DCB*.{[C.N. 5]}"),
        s(2, "Thus, *CDB* is much greater than *DCB*.{[C.N. 5]}"),
        s(2, "Again, since *CB* is equal to *DB*, the angle *CDB* is also equal to angle *DCB*.{[Prop. 1.5]}"),
        s(2, "But it was shown that the former (angle) is also much greater (than the latter)."),
        s(2, "The very thing is impossible."),
        s(3, "Thus, on the same straight-line, two other straight-lines equal, respectively, to two (given) straight-lines (which meet) cannot be constructed (meeting) at a different point on the same side (of the straight-line), but having the same ends as the given straight-lines."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_8: Proposition = Proposition {
    book: 1,
    number: 8,
    enunciation: "If two triangles have two sides equal to two sides, respectively, and also have the base equal to the base, then they will also have equal the angles encompassed by the equal straight-lines.",
    figure: book1_prop8,
    phrases: &[
        s(1, "Let *ABC* and *DEF* be two triangles having the two sides *AB* and *AC* equal to the two sides *DE* and *DF*, respectively."),
        s(1, "(That is) *AB* to *DE*, and *AC* to *DF*."),
        s(1, "Let them also have the base *BC* equal to the base *EF*."),
        s(1, "I say that the angle *BAC* is also equal to the angle *EDF*."),
        s(2, "For if triangle *ABC* is applied to triangle *DEF*, the point *B* being placed on point *E*, and the straight-line *BC* on *EF*,"),
        s(2, "then point *C* will also coincide with *F*, on account of *BC* being equal to *EF*."),
        s(2, "So (because of) *BC* coinciding with *EF*, (the sides) *BA* and *CA* will also coincide with *ED* and *DF* (respectively)."),
        s(2, "For if base *BC* coincides with base *EF*, but the sides *AB* and *AC* do not coincide with *ED* and *DF* (respectively), but miss like *EG* and *GF* (in the above figure),"),
        s(2, "then we will have constructed upon the same straight-line, two other straight-lines equal, respectively, to two (given) straight-lines,"),
        s(2, "and (meeting) at a different point on the same side (of the straight-line), but having the same ends."),
        s(2, "But (such straight-lines) cannot be constructed.{[Prop. 1.7]}"),
        s(2, "Thus, the base *BC* being applied to the base *EF*, the sides *BA* and *AC* cannot not coincide with *ED* and *DF* (respectively)."),
        s(2, "Thus, they will coincide."),
        s(2, "So the angle *BAC* will also coincide with angle *EDF*, and will be equal to it.{[C.N. 4]}"),
        s(3, "Thus, if two triangles have two sides equal to two side, respectively, and have the base equal to the base,"),
        s(3, "then they will also have equal the angles encompassed by the equal straight-lines."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_9: Proposition = Proposition {
    book: 1,
    number: 9,
    enunciation: "To cut a given rectilinear angle in half.",
    figure: book1_prop9,
    phrases: &[
        s(1, "Let *BAC* be the given rectilinear angle."),
        s(1, "So it is required to cut it in half."),
        s(2, "Let the point *D* have been taken at random on *AB*, and let *AE*, equal to *AD*, have been cut off from *AC,*{[Prop. 1.3]} and let *DE* have been joined."),
        s(2, "And let the equilateral triangle *DEF* have been constructed upon *DE,*{[Prop. 1.1]} and let *AF* have been joined."),
        s(2, "I say that the angle *BAC* has been cut in half by the straight-line *AF*."),
        s(3, "For since *AD* is equal to *AE*, and *AF* is common, the two (straight-lines) *DA*, *AF* are equal to the two (straight-lines) *EA*, *AF*, respectively."),
        s(3, "And the base *DF* is equal to the base *EF*."),
        s(3, "Thus, angle *DAF* is equal to angle *EAF*.{[Prop. 1.8]}"),
        s(4, "Thus, the given rectilinear angle *BAC* has been cut in half by the straight-line *AF*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_10: Proposition = Proposition {
    book: 1,
    number: 10,
    enunciation: "To cut a given finite straight-line in half.",
    figure: book1_prop10,
    phrases: &[
        s(1, "Let *AB* be the given finite straight-line."),
        s(1, "So it is required to cut the finite straight-line *AB* in half."),
        s(2, "Let the equilateral triangle *ABC* have been constructed upon (*AB*),{[Prop. 1.1]} and let the angle *ACB* have been cut in half by the straight-line *CD*.{[Prop. 1.9]}"),
        s(2, "I say that the straight-line *AB* has been cut in half at point *D*."),
        s(3, "For since *AC* is equal to *CB*, and *CD* (is) common, the two (straight-lines) *AC*, *CD* are equal to the two (straight-lines) *BC*, *CD*, respectively."),
        s(3, "And the angle *ACD* is equal to the angle *BCD*."),
        s(3, "Thus, the base *AD* is equal to the base *BD*.{[Prop. 1.4]}"),
        s(4, "Thus, the given finite straight-line *AB* has been cut in half at (point) *D*."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_11: Proposition = Proposition {
    book: 1,
    number: 11,
    enunciation: "To draw a straight-line at right-angles to a given straight-line from a given point on it.",
    figure: book1_prop11,
    phrases: &[
        s(1, "Let *AB* be the given straight-line, and *C* the given point on it."),
        s(1, "So it is required to draw a straight-line from the point *C* at right-angles to the straight-line *AB*."),
        s(2, "Let the point *D* be have been taken at random on *AC*, and let *CE* be made equal to *CD,*{[Prop. 1.3]} and let the equilateral triangle *FDE* have been constructed on *DE,*{[Prop. 1.1]} and let *FC* have been joined."),
        s(2, "I say that the straight-line *FC* has been drawn at right-angles to the given straight-line *AB* from the given point *C* on it."),
        s(3, "For since *DC* is equal to *CE*, and *CF* is common, the two (straight-lines) *DC*, *CF* are equal to the two (straight-lines) *EC*, *CF*, respectively."),
        s(3, "And the base *DF* is equal to the base *FE*."),
        s(3, "Thus, the angle *DCF* is equal to the angle *ECF*,{[Prop. 1.8]} and they are adjacent."),
        s(3, "But when a straight-line stood on a(nother) straight-line makes the adjacent angles equal to one another, each of the equal angles is a right-angle.{[Def. 1.10]}"),
        s(3, "Thus, each of the (angles) *DCF* and *FCE* is a right-angle."),
        s(4, "Thus, the straight-line *CF* has been drawn at right-angles to the given straight-line *AB* from the given point *C* on it."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_12: Proposition = Proposition {
    book: 1,
    number: 12,
    enunciation: "To draw a straight-line perpendicular to a given infinite straight-line from a given point which is not on it.",
    figure: book1_prop12,
    phrases: &[
        s(1, "Let *AB* be the given infinite straight-line and *C* the given point, which is not on (*AB*)."),
        s(1, "So it is required to draw a straight-line perpendicular to the given infinite straight-line *AB* from the given point *C*, which is not on (*AB*)."),
        s(2, "For let point *D* have been taken at random on the other side (to *C*) of the straight-line *AB*, and let the circle *EFG* have been drawn with center *C* and radius *CD,*{[Post. 3]} and let the straight-line *EG* have been cut in half at (point) *H,*{[Prop. 1.10]} and let the straight-lines *CG*, *CH*, and *CE* have been joined."),
        s(2, "I say that the (straight-line) *CH* has been drawn perpendicular to the given infinite straight-line *AB* from the given point *C*, which is not on (*AB*)."),
        s(3, "For since *GH* is equal to *HE*, and *HC* (is) common, the two (straight-lines) *GH*, *HC* are equal to the two (straight-lines) *EH*, *HC*, respectively, and the base *CG* is equal to the base *CE*."),
        s(3, "Thus, the angle *CHG* is equal to the angle *EHC,*{[Prop. 1.8]} and they are adjacent."),
        s(3, "But when a straight-line stood on a(nother) straight-line makes the adjacent angles equal to one another, each of the equal angles is a right-angle, and the former straight-line is called a perpendicular to that upon which it stands.{[Def. 1.10]}"),
        s(4, "Thus, the (straight-line) *CH* has been drawn perpendicular to the given infinite straight-line *AB* from the given point *C*, which is not on (*AB*)."),
        s(4, "(Which is) the very thing it was required to do."),
    ],
};

pub const PROP_13: Proposition = Proposition {
    book: 1,
    number: 13,
    enunciation: "If a straight-line stood on a(nother) straight-line makes angles, it will certainly either make two right-angles, or (angles whose sum is) equal to two right-angles.",
    figure: book1_prop13,
    phrases: &[
        s(1, "For let some straight-line *AB* stood on the straight-line *CD* make the angles *CBA* and *ABD*."),
        s(1, "I say that the angles *CBA* and *ABD* are certainly either two right-angles, or (have a sum) equal to two right-angles."),
        s(2, "In fact, if *CBA* is equal to *ABD* then they are two right-angles.{[Def. 1.10]}"),
        s(2, "But, if not, let *BE* have been drawn from the point *B* at right-angles to *CD*.{[Prop. 1.11]}"),
        s(2, "Thus, *CBE* and *EBD* are two right-angles."),
        s(2, "And since *CBE* is equal to the two (angles) *CBA* and *ABE*, let *EBD* have been added to both."),
        s(2, "Thus, the (sum of the angles) *CBE* and *EBD* is equal to the (sum of the) three (angles) *CBA*, *ABE*, and *EBD*.{[C.N. 2]}"),
        s(2, "Again, since *DBA* is equal to the two (angles) *DBE* and *EBA*, let *ABC* have been added to both."),
        s(2, "Thus, the (sum of the angles) *DBA* and *ABC* is equal to the (sum of the) three (angles) *DBE*, *EBA*, and *ABC*.{[C.N. 2]}"),
        s(2, "But (the sum of) *CBE* and *EBD* was also shown (to be) equal to the (sum of the) same three (angles)."),
        s(2, "And things equal to the same thing are also equal to one another.{[C.N. 1]}"),
        s(2, "Therefore, (the sum of) *CBE* and *EBD* is also equal to (the sum of) *DBA* and *ABC*."),
        s(2, "But, (the sum of) *CBE* and *EBD* is two right-angles."),
        s(2, "Thus, (the sum of) *ABD* and *ABC* is also equal to two right-angles."),
        s(3, "Thus, if a straight-line stood on a(nother) straight-line makes angles, it will certainly either make two right-angles, or (angles whose sum is) equal to two right-angles."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_14: Proposition = Proposition {
    book: 1,
    number: 14,
    enunciation: "If two straight-lines, not lying on the same side, make adjacent angles (whose sum is) equal to two right-angles with some straight-line, at a point on it, then the two straight-lines will be straight-on (with respect) to one another.",
    figure: book1_prop14,
    phrases: &[
        s(1, "For let two straight-lines *BC* and *BD*, not lying on the same side, make adjacent angles *ABC* and *ABD* (whose sum is) equal to two right-angles with some straight-line *AB*, at the point *B* on it."),
        s(1, "I say that *BD* is straight-on with respect to *CB*."),
        s(2, "For if *BD* is not straight-on to *BC* then let *BE* be straight-on to *CB*."),
        s(3, "Therefore, since the straight-line *AB* stands on the straight-line *CBE*, the (sum of the) angles *ABC* and *ABE* is thus equal to two right-angles.{[Prop. 1.13]}"),
        s(3, "But (the sum of) *ABC* and *ABD* is also equal to two right-angles."),
        s(3, "Thus, (the sum of angles) *CBA* and *ABE* is equal to (the sum of angles) *CBA* and *ABD*.{[C.N. 1]}"),
        s(3, "Let (angle) *CBA* have been subtracted from both."),
        s(3, "Thus, the remainder *ABE* is equal to the remainder *ABD*,{[C.N. 3]} the lesser to the greater."),
        s(3, "The very thing is impossible."),
        s(3, "Thus, *BE* is not straight-on with respect to *CB*."),
        s(3, "Similarly, we can show that neither (is) any other (straight-line) than *BD*."),
        s(3, "Thus, *CB* is straight-on with respect to *BD*."),
        s(4, "Thus, if two straight-lines, not lying on the same side, make adjacent angles (whose sum is) equal to two right-angles with some straight-line, at a point on it, then the two straight-lines will be straight-on (with respect) to one another."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_15: Proposition = Proposition {
    book: 1,
    number: 15,
    enunciation: "If two straight-lines cut one another then they make the vertically opposite angles equal to one another.",
    figure: book1_prop15,
    phrases: &[
        s(1, "For let the two straight-lines *AB* and *CD* cut one another at the point *E*."),
        s(1, "I say that angle *AEC* is equal to (angle) *DEB*, and (angle) *CEB* to (angle) *AED*."),
        s(2, "For since the straight-line *AE* stands on the straight-line *CD*, making the angles *CEA* and *AED*, the (sum of the) angles *CEA* and *AED* is thus equal to two right-angles.{[Prop. 1.13]}"),
        s(2, "Again, since the straight-line *DE* stands on the straight-line *AB*, making the angles *AED* and *DEB*, the (sum of the) angles *AED* and *DEB* is thus equal to two right-angles.{[Prop. 1.13]}"),
        s(2, "But (the sum of) *CEA* and *AED* was also shown (to be) equal to two right-angles."),
        s(2, "Thus, (the sum of) *CEA* and *AED* is equal to (the sum of) *AED* and *DEB*.{[C.N. 1]}"),
        s(2, "Let *AED* have been subtracted from both."),
        s(2, "Thus, the remainder *CEA* is equal to the remainder *BED*.{[C.N. 3]}"),
        s(2, "Similarly, it can be shown that *CEB* and *DEA* are also equal."),
        s(3, "Thus, if two straight-lines cut one another then they make the vertically opposite angles equal to one another."),
        s(3, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_16: Proposition = Proposition {
    book: 1,
    number: 16,
    enunciation: "For any triangle, when one of the sides is produced, the external angle is greater than each of the internal and opposite angles.",
    figure: book1_prop16,
    phrases: &[
        s(1, "Let *ABC* be a triangle, and let one of its sides *BC* have been produced to *D*."),
        s(1, "I say that the external angle *ACD* is greater than each of the internal and opposite angles, *CBA* and *BAC*."),
        s(2, "Let the (straight-line) *AC* have been cut in half at (point) *E*.{[Prop. 1.10]}"),
        s(2, "And *BE* being joined, let it have been produced in a straight-line to (point) *F*."),
        s(2, "And let *EF* be made equal to *BE*,{[Prop. 1.3]} and let *FC* have been joined, and let *AC* have been drawn through to (point) *G*."),
        s(3, "Therefore, since *AE* is equal to *EC*, and *BE* to *EF*, the two (straight-lines) *AE*, *EB* are equal to the two (straight-lines) *CE*, *EF*, respectively."),
        s(3, "Also, angle *AEB* is equal to angle *FEC*, for (they are) vertically opposite.{[Prop. 1.15]}"),
        s(3, "Thus, the base *AB* is equal to the base *FC*, and the triangle *ABE* is equal to the triangle *FEC*, and the remaining angles subtended by the equal sides are equal to the corresponding remaining angles.{[Prop. 1.4]}"),
        s(3, "Thus, *BAE* is equal to *ECF*."),
        s(3, "But *ECD* is greater than *ECF*."),
        s(3, "Thus, *ACD* is greater than *BAE*."),
        s(3, "Similarly, by having cut *BC* in half, it can be shown (that) *BCG*—that is to say, *ACD*—(is) also greater than *ABC*."),
        s(4, "Thus, for any triangle, when one of the sides is produced, the external angle is greater than each of the internal and opposite angles."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROP_17: Proposition = Proposition {
    book: 1,
    number: 17,
    enunciation: "For any triangle, (the sum of) two angles taken together in any (possible way) is less than two right-angles.",
    figure: book1_prop17,
    phrases: &[
        s(1, "Let *ABC* be a triangle."),
        s(1, "I say that (the sum of) two angles of triangle *ABC* taken together in any (possible way) is less than two right-angles."),
        s(2, "For let *BC* have been produced to *D*."),
        s(3, "And since the angle *ACD* is external to triangle *ABC*, it is greater than the internal and opposite angle *ABC*.{[Prop. 1.16]}"),
        s(3, "Let *ACB* have been added to both."),
        s(3, "Thus, the (sum of the angles) *ACD* and *ACB* is greater than the (sum of the angles) *ABC* and *BCA*."),
        s(3, "But, (the sum of) *ACD* and *ACB* is equal to two right-angles.{[Prop. 1.13]}"),
        s(3, "Thus, (the sum of) *ABC* and *BCA* is less than two right-angles."),
        s(3, "Similarly, we can show that (the sum of) *BAC* and *ACB* is also less than two right-angles, and further (that the sum of) *CAB* and *ABC* (is less than two right-angles)."),
        s(4, "Thus, for any triangle, (the sum of) two angles taken together in any (possible way) is less than two right-angles."),
        s(4, "(Which is) the very thing it was required to show."),
    ],
};

pub const PROPOSITIONS: &[Proposition] = &[
    PROP_1, PROP_2, PROP_3, PROP_4, PROP_5, PROP_6, PROP_7, PROP_8, PROP_9, PROP_10, PROP_11,
    PROP_12, PROP_13, PROP_14, PROP_15, PROP_16, PROP_17,
];
